### ISSUE TITLE
Request: Advanced Guidance Chip

### ISSUE THREAD

**Issue by IMarvinTPA** [Advanced-Rocketry/AdvancedRocketry#1021]
Minecraft Version: 1.12.2
-
Forge Version:  2555
-
Advanced Rocketry Version:  42
-
LibVulpes Version: 2.7.24
-
**is this the latest curseforge build?** Yes

Explain issue in detail:
Discussed briefly in https://github.com/zmaster587/AdvancedRocketry/issues/1019
How about an "Advanced Rocket Guidance Chip" or "Programmable Rocket Guidance Chip"
Takes one of each Planet and Station ID chips (unprogrammed) and maybe other bits.
Has 2, 10, or 25 memory locations that can be programmed by right clicking on a docking pad or launch pad.

Thanks,
IMarv

**Comment by voidsong-dragonfly** [comment]
Just use the linker + removable and reprogrammable system with chips to do this. No specified chip.
