### ISSUE TITLE
enhancement: Asteroids crash down on planets

### ISSUE THREAD

**Issue by Jummit** [Advanced-Rocketry/AdvancedRocketry#1042]
With the comet system we have now, there is distance, mass and so on. Maybe, if a comet has specific stats, it could crash down on planets with craters and no atmosphere and leave the resources the comet is made of in a crater.

**Comment by nonenothing** [comment]
> crash down on planets with craters

https://www.curseforge.com/minecraft/mc-mods/falling-meteors-mod

**Comment by Jummit** [comment]
Nah. The best thing about this would be that you can configure it yourself and affecting the falling comets and the ones that you can research.

**Comment by nonenothing** [comment]
Why so serious?

**Comment by Jummit** [comment]
Oh, sorry if this provoked you, it wasn't meant so. I was just annoyed that every suggestion I bring here leaves me with a link to a mod that implements it, but does not have any AR compatibility.

**Comment by zmaster587** [comment]
I not quite sure I follow the relationship between falling meteors and the asteroids that can be discovered in the observatory.  Would it be possible to elaborate on that.

I do like the idea, would be a great benefit for planets with low atmospheres much like the geodes spawn on high pressure planets.  I'm just still not sure when I can get around to actually adding stuff with so much that needs fixing.

**Comment by Jummit** [comment]
Its just an idea. It isn't like everything that sounds cool has to be added instantly. Bugfixes are probably a better addition to the mod than this.

**Comment by CTH999** [comment]
So, you can mine Asteroids. By comets they mean asteroids, because a comet needs a tail, but besides that it's an asteroid. So, basically, they sometimes crash, and land on the planet. Makes sense to me.

**Comment by voidsong-dragonfly** [comment]
Craters now have their ores definable per-planet in the XML. Having asteroid spawn their ores is.... iffy, because they can take itemstacks. This is (overall) the better route.
