### ISSUE TITLE
More detail on linkers for where the linked block is

### ISSUE THREAD

**Issue by IMarvinTPA** [Advanced-Rocketry/AdvancedRocketry#1047]
Minecraft Version: 1.12.2
-
Forge Version: 2555
-
Advanced Rocketry Version:  45
-
LibVulpes Version:  24
-
**is this the latest curseforge build?**  Yes

Explain issue in detail:
I quickly forget where my linkers point.  If they could include Planet/Station and Pad Name, that would help a lot.

IMarv

**Comment by voidsong-dragonfly** [comment]
Dimension is already included in them.
