### ISSUE TITLE
Biome Generation

### ISSUE THREAD

**Issue by jelaw21** [Advanced-Rocketry/AdvancedRocketry#1072]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.1.2590
Advanced Rocketry Version:
- 1.2.6-49 UNSTABLE
LibVulpes Version:
- 0.2.7-25 UNSTABLE
**is this the latest curseforge build?**

# Explain issue in detail:
I have created a number of planets from the planetDefs.xml. Everything is working out fine, but all the biomes seem to be VERY close together, like maybe 10 to 12 blocks between 3 or 4 of them. I have included a picture showing a marsh, a deep swamp and a ocean spire biome very close.
![2018-01-16_16 11 34](https://user-images.githubusercontent.com/21100827/35012519-f88128c4-fad7-11e7-838c-78b23fbb898d.png)

I know biome generation is random, but I have generated 4 or 5 planets and all of them, throughout the 1000 block radius I ran, yields the same very close biomes.  Here's my .xml (in txt format)
[planetDefs.txt](https://github.com/zmaster587/AdvancedRocketry/files/1636847/planetDefs.txt)

**Comment by voidsong-dragonfly** [comment]
Can no longer replicate. Probably got fixed in the middle of other 1.12 terrain gen fixes.
