### ISSUE TITLE
[Bug?] Atmosphere Density <75 but still breathable

### ISSUE THREAD

**Issue by lolmetimbers** [Advanced-Rocketry/AdvancedRocketry#1091]
Minecraft Version:
1.10.2

Under website guide it says . _Any value less than 75 is unbreathable and will require a spacesuit._ but I have set this to 59 and 65 and the air is still breathable. Not sure what the lower value breakpoint is.

If you can, I suggest to split atmosphere density and breathability as high density atmosphere planets can able be unbreathable e.g. Venus has a very dense atmosphere but you cannot breathe because it is carbon dioxide. A split in configs is also better as fog density is linked directly to atmosphere density which would allow for more customization. Many thanks

**Comment by zmaster587** [comment]
The lower bound is 25 now, it got changed a while back and I forgot to update the wiki.

I can decouple the fog and atm density, I'll work on that when i get time.

**Comment by Axieum** [comment]
Cannot agree any further! Splitting the breathability into its own configurable property will allow much nicer worlds. I've currently run into a standpoint, as I want to disable breathing on the overworld but still maintain nice skies (not like I'm in space). Furthermore, I think you should add an invert option to the `entityAtmBypass` blacklist to a whitelist; this will allow for only the player to suffocate and animals/mobs not to.

I've been using Galacticraft's oxygen system, though want to change to Advanced Rocketry as it seems much more flexible and interesting. Should you add this oxygen change separate to the atmospheric density I'd be very happy.

**Comment by zmaster587** [comment]
One thing I've been planning to do for a while is to allow specification of the atmosphere type in the planetDefs.xml.  That would also decouple atm pressure from breathability, so that should fix the problem with the skies.  An invert option for the whitelist would be doable, sure.

**Comment by Axieum** [comment]
Sounds good! Glad you're looking into this.

**Comment by EnderN3x** [comment]
Is there perhaps any news on decoupling breathable from atmosphereDensity?

**Comment by Gliese-832-c** [comment]
Perhaps this should be closed?
