### ISSUE TITLE
Is there a way to have each player have their own planet?

### ISSUE THREAD

**Issue by Axieum** [Advanced-Rocketry/AdvancedRocketry#1119]
On a multiplayer server, I'd like for each player to have their own planet created and registered with Adv. Rocketry when they login.

Hopefully, this world will be treated the same as the overworld (structure spawning, etc.).

**Comment by Jummit** [comment]
You can do that with computercraft command computers or a server plugin. That's just my solution as long as this is no option in the mod. If you have computercraft and want to have a script that teleports new players to they're planet, you can ask me.

**Comment by Axieum** [comment]
@Jummit We are using OpenComputers. Still possible?
