### ISSUE TITLE
Suggestion- Weapons+ Tools+ Combat+ Compatability

### ISSUE THREAD

**Issue by CTH999** [Advanced-Rocketry/AdvancedRocketry#1156]
So, I like this mod because it's like [The Warp Drive Mod](https://minecraft.curseforge.com/projects/warpdrive) Only updated regularly! However, it would be nice to run into other players in space, and be able to work together, connect you ships, board other vessels, track enemy's and attack later, and board+ Steal parts!

Also, this would work quite nicely with this suggestion! [Computer Craft (And hopefully Open Computers) Support](https://github.com/zmaster587/AdvancedRocketry/issues/147) Since you could use computers to make warp misles. viruses, control weapons, and more!
There could also be missles, [Guns](https://www.livescience.com/18588-shoot-gun-space.html) short-range teleporters, long range but easier to block teleporters!
This would also work well with [Hard Mod](https://github.com/zmaster587/AdvancedRocketry/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22HardMode+update%22) (In my opinion, that is)

Also, what about High-Tier iridium tools (Like picks) And armor. Also, a space suit upgrade for [Modular Power Suits](https://minecraft.curseforge.com/projects/modular-powersuits?gameCategorySlug=mc-mods&projectID=235442) Allowing you to be much more powerful! (And therefore much better with combat)

And of course, compat with [Draconic Evouloution](https://minecraft.curseforge.com/projects/draconic-evolution?gameCategorySlug=mc-mods&projectID=223565) (Especially [This Suggestion](https://github.com/brandon3055/Draconic-Evolution/issues/1050))
Also, some of these could benefit from [Exotic Matter](https://github.com/zmaster587/AdvancedRocketry/issues/945)
Also, lasers could have different types.

This could also work well with[[sugesstion] adding tier thrusters and etc](https://github.com/zmaster587/AdvancedRocketry/issues/234) And [[Suggestion] Space Travel](https://github.com/zmaster587/AdvancedRocketry/issues/11) [Transporters for Space Ships](https://github.com/zmaster587/AdvancedRocketry/issues/410) and [Suggestion- AR Comatability](https://github.com/LemADEC/WarpDrive/issues/311)

However, this is just a suggestion

(I just noticed, it's similar to [[enhancement] Lasers and shields!](https://github.com/zmaster587/AdvancedRocketry/issues/846), but slightly different!

**Comment by CTH999** [comment]
Also, compatibility with [Valkyrein Warefare](https://minecraft.curseforge.com/projects/valkyrien-warfare?gameCategorySlug=mc-mods&projectID=258371l) Similar to [Suggestion- AR Compat](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/130). As mentioned there, VW Ships would have some features AR ships don't, and visa-versa.

**Comment by CTH999** [comment]
Thanks Again!

**Comment by voidsong-dragonfly** [comment]
AR is a peaceful mod and will not include weapons. As for space travel and encountering other players, this is also not possible at the current time.
