### ISSUE TITLE
[Feature Request] Minor UX changes.

### ISSUE THREAD

**Issue by C1ffisme** [Advanced-Rocketry/AdvancedRocketry#1167]
There are a lot of suggestions for this mod, and rightfully so. A mod centered around going to space is going to have a lot of suggestions incoming. But before any of that gets implemented, there are a lot of little problems with the mod that should be fixed to make life easier.

I've been composing a list just to have something devs can check. A lot of these have to do with making the player not have to check wikis or video tutorials, some of them are just to remove annoying behavior or add expected behavior.

~~(This was using 1.10.2, latest CurseForge build, not the latest compiled build.)~~

(Updated using the latest CurseForge build for 1.12.2 as of January 19th, 2020)

# Immediate Concerns:

- [x] The Plate Presser should specify that it needs obsidian.
- [x] The Rolling Machine's inputs **and outputs** do not have holes where holes should be. Adding the hole texture there would remove some confusion.
- [x] The player should be allowed to right-click fluid inputs/outputs with a bucket and not have to interact with the GUI. This is especially annoying when you need to input a lot of fluid.
- [ ] Fluid inputs and outputs have the same text at the top of their GUI, which makes it hard to tell what you're interacting with on a multiblock that doesn't show you the input/output textures.
- [ ] The Atmosphere Analyzer GUI can cover up the Health Bar. As you can imagine, this is not good.
- [x] The Space Suit GUI appears in Spectator mode when it is not needed.
- [x] The Satellite Builder needs to tell the player through lore text or otherwise that it needs a power plug placed below it.
- [x] If a Satellite has no data storage or no power storage, the satellite builder should refuse to build the satellite in order to stop the player from building a useless satellite.
- [ ] The "Process Discovery" button on the Observatory doesn't actually look like a button.
- [ ] Many buttons such as the "Process Discovery" button in the Observatory or the "Build Sattelite" button in the Sattelite Builder do not provide feedback as to why they aren't doing anything.
- [ ] When making the Atmosphere Converter, the holographic clay looks a little bit too similar to the holographic concrete. Considering how huge the structure is, it can be frustrating not knowing which block you placed wrongly.
- [x] The "First block of a Cable must be powered" rule is never explained in-game. At the very least lore text would be preferred. Better yet would be to remove this rule and add "gates" that can be switched on and off with redstone.
- [x] In the Creative Inventory at the bottom of the Miscellaneous section there are five purple and black blocks that are completely invisible when placed. These seem to represent liquid forms of the five liquids. It would probably be best to remove them from the Creative inventory if possible.
- [x] The Bionic Leg upgrade can be crafted in the precision assembling machine using a motor and a control circuit. Alternatively, you can craft it in the precision assembling machine using a motor, a control circuit, AND an advanced circuit.

# Less Important Concerns:
- [x] The Coal Generator and Plate Presser textures are no different from their Vanilla derivatives. This isn't a huge issue, considering it's a sin even Vanilla Minecraft is guilty of, but I'd like to see it fixed sometime.
- [x] When using the cutting machine, you see the output item being cut. Preferably I'd like to see the input item disappear when leaving the saw and an output item appears, but replacing this with the input item works too.
- [x] The Precision Assembler can have fluid inputs built into it, but none of its default recipes require any liquids. (This might be intentional?)
- [x] The seat in the inventory looks exactly like a grey carpet. It might be worth changing it just a bit for the sake of it.
- [x] The seat is also crafted in the way other mods might expect a wool slab to be crafted. It might be worth changing the default recipe to avoid possible conflicts.
- [x] When right-clicking a rocket with no seat, the inventory GUI should appear even if the player is not sneak-clicking the rocket.
- [ ] When building the microwave receiver, the ghost microwave receiver block looks no different from the ghost solar panel blocks. It might be nice to at least have something to suggest the block is different.
- [ ] Speaking of which, placing it in the middle might be a bad idea considering what happens if you
stand on an active receiver.
- [x] The Asteroid Chip and the Space Station chip are the same color.
- [x] The Docking pad is sometimes referred to as a "Landing Pad". Can we choose just one name for it and use that in Documentation and Code?

# Compatability Concerns:

- [ ] Rutile ore can be smelted in Thermal Expansion's Induction Smelter, which is much faster than smelting it in the Arc Furnace and isn't gated behind the Nether. (Thermal Expansion)
- [ ] Even worse, the ore can be pulverized with an Immersive Engineering hammer or other pulverizer and the dust can be smelted in a vanilla furnace. (Immersive Engineering or any mod that adds a pulverizer)
- [x] Right-clicking on a Thermal Expansion tank with a tank of Hydrogen, Rocket Fuel, etc, doesn't insert the fluid into the TE tank. (Thermal Expansion)
- [x] Elytra Wings can catch air in a vacuum. This is an unlikely event in Survival Mode, although it can happen in Creative Mode. And who knows, maybe the player has a Chestplate + Elytra mod which can be air-sealed? **EDIT: if the gravity is lower than around 75% Earth Gravity, the player will fly upwards indefinitely without coming down.** (Vanilla)
- [x] Falling Blocks, Minecarts, Boats, and Arrows do not respect non-Earth gravity. (Vanilla)
- [x] In JEI, the recipe for a metal plate in the rolling machine appears twice, once requiring water and once not requiring water, despite the fact that trying to craft plates without using water doesn't work. (JEI)
- [ ] We seem to have some IC2 Compatability. In order to further this compatability, it might be nice to allow the usage of their hydrogen and oxygen in Advanced Rocketry Recipes. (IC2)
- [ ] None of the machines have a button in their GUI that you can click to see a list of JEI recipes that are possible with that machine. (JEI)

# Thoughts / Extra Credit?
- [x] Immersive Engineering has very similar coil blocks. It might be cool to add some compatibility here...
- [ ] One piece of coal in an unaltered Steam Dynamo from Thermal Expansion gives the player 21000 RF. One piece of coal in the rather cheap Coal Generator gives the player about 64000 RF. This also happens to be more than the entire internal buffer of the Generator.
- [ ] (Wiki Issue) Concrete, Geodes, Crystal Blocks, and Station Lights don't have wiki pages. Although they aren't useful for anything outside of decoration, wouldn't it be nice to have a wiki page documenting each of these?
- [x] (#1221) In order to make it easier to remember which randomly generated planet you built a base on, it might be nice to make a very simple random name generator, or at least each planet should be named "Starname - (Letter)" similar to exoplanet naming rather than "Sol - (number)".
- [ ] In addition to that, it might be nice if the orbits of planets were drawn in the planet selection screen, with the planets each at a reasonable distance from each other to give the planets a more memorable order.
- [ ] In the Astrobody Data Processor, the output arrow buttons for Data Storage Units say they output to "chips" rather than "Data Storage Units". This is confusing since the mod already contains completely different items called "chips"
- [x] Should Multiblock Core blocks be labeled as such in the lore text?

**Comment by C1ffisme** [comment]
Just thought of another idea that belongs in the Thoughts and Extra Credit category, should multiblock cores be labeled as such (through lore text) to avoid confusion? This might be a little less confusing, although it's not super-high priority since some of the pre-download screenshots on curseforge showcase the multiblocks.

**Comment by sdfg2** [comment]
With regards to JEI having recipes with and without water - I really like that.  I've got water pumped in constantly to the rolling machine, so when it comes to create patterns for Refined Storage crafters, it's much simpler then having to remember to remove the water requirement every time.

**Comment by C1ffisme** [comment]
@sdfg2 Ok, properly interacting with Refined Storage is great, but JEI is used by every modded Minecraft player and their mom. These redundant duplicate recipes look strange to the end user and just look unprofessional and low-quality.

**Comment by C1ffisme** [comment]
Added a new one: The Bionic Leg upgrade can be crafted in the precision assembling machine using a motor and a control circuit. Alternatively, you can craft it in the precision assembling machine using a motor, a control circuit AND an advanced circuit.

**Comment by C1ffisme** [comment]
Testing in 1.12.2: 

- Multiblock cores do specify that they are multiblock cores. I'd still like it if the Sattelite Builder specified it needed a power input, but this does knock off one of the checkboxes.

- I decided to add that the "Process Discovery" button doesn't really specify when something is preventing it from working.

- The bionic leg thing is fixed

**Comment by Silfryi** [comment]
The problem with the ore processing isn't easily fixable, it's registered as `oreTitanium` as it should be, because it is an ore of Titanium. The other mods trawl the OD for matching ore:dust or ore:ingot things and pull from there, and without removing OD compatibility from either thing, which isn't something that should happen/have to happen.

**Comment by C1ffisme** [comment]
> without removing OD compatibility from either thing, which isn't something that should happen/have to happen, there's no way to prevent that.

I think from a logical point of view, removing Titanium ore from the registry might actually be the correct move here if the idea is "Titanium Ore should not be easily smelted by other mods". That being said I understand that to not register it with the ore dictionary would seem odd. (Perhaps an `oreRutile` definition rather than an `oreTitanium` one, to signify how the Titanium is embedded in a mineral that requires high-powered smelting?)

**Comment by Silfryi** [comment]
@C1ffisme since I apparently can't check your boxes for you, would you mind going through on the 2.0.0 update with the latest LV and checking all that are now fuffilled? Most are.

**Comment by voidsong-dragonfly** [comment]
Closed for #2115
