### ISSUE TITLE
Feature Request: Space Biomes, Endor, and Laying Claim to Planets

### ISSUE THREAD

**Issue by Keetarin** [Advanced-Rocketry/AdvancedRocketry#1223]
It would be nice if you created a biome specifically for space (It's basically a single biome anyhow), it would be handy for packs that include Tough as Nails and would allow the pack makers to customize how TAN treats temperatures in space.
The biome(s) could be divided into three basic sectors based on the distance from the star systems center.
Hot Zone: Basically where you would find Venus and other Hot planets like it, generally closer to the star than the overworld
Goldilocks Zone a.k.a. Overworld Zone: Between the Cold and Hot zones and where the overworld and similar worlds would be by default.
Cold Zone: Basically where Neptune and other Cold Planets would be found by default, generally far away from the center.
In Addition, the moons around Gas Giants, would have their own zones due to the effect of gravity and heat from said giants.
It would make it very interesting to see a Jungle Moon (basically Endor from star wars) around a Gas Giant which is in it's systems Cold Zone. Planetary Moons could be coded as being planets orbiting Gas Giants for world generation and mapping (basically moons around gas giants would have a chance of being generated as planets, essentially being the larger moons and in the case of smaller rocky planets it would be at most a planets twin).

Edit: just thought of it afterwords, could it be possible to "lay claim" to a planet and name it using an item, all it would do is change the displayed name, but it would still be fun, you'd have to limit it to the first time only (or multiple times in the case of OP commands).
Heck it could even be configurable on whether it shows to other players on the server and whether it can be changed once, multiple times, or at all.

**Comment by C1ffisme** [comment]
> It would be nice if you created a biome specifically for space (It's basically a single biome anyhow),

[This is already implemented.](http://65.78.115.159:8000/AdvancedRocketry/misc/Biomes.php) See under "Space".

> The biome(s) could be divided into three basic sectors based on the distance from the star systems center.
Hot Zone: Basically where you would find Venus and other Hot planets like it, generally closer to the star than the overworld
Goldilocks Zone a.k.a. Overworld Zone: Between the Cold and Hot zones and where the overworld and similar worlds would be by default.
Cold Zone: Basically where Neptune and other Cold Planets would be found by default, generally far away from the center.

Before we do this, can we improve how objects are rendered in the map of planets? Currently the distance limit for planets is 2 AU, and anything higher doesn't work on the map for some reason. [Also, Wikipedia has a nice equation for calculating the temperature of a planet based on Orbital Distance, Star Luminosity and Albedo.](https://en.wikipedia.org/wiki/Effective_temperature#Blackbody_Temperature)

> In Addition, the moons around Gas Giants, would have their own zones due to the effect of gravity and heat from said giants.

It would make more sense for moons to be heated by the sun, the tidal effects from a gas giant might heat up a planet, but they'd also make the planet have bad geological activity. (Earthquakes, etc.)

> Edit: just thought of it afterwords, could it be possible to "lay claim" to a planet and name it using an item, all it would do is change the displayed name, but it would still be fun, you'd have to limit it to the first time only (or multiple times in the case of OP commands).

That could be cool. I'm not sure why you put this in the same post about planet and moon biome temperature, though.

**Comment by Keetarin** [comment]
Didn't know about the space biome...
still would be nice to have planetary moons though (I want to lay claim to Endor! LOL), oh and the reason the laying claim part was in this post as well was because I had been thinking about things that would be interesting to put in, but was unable to remember what the third idea I had was.
So, what or how do you think you'd make claims in the mod, personally I'd make a flag, a memorial (basically a sign that says something along the lines of "Welcome to ______, Kilroy was here!" or something ("Kilroy was Here!" would be in graffiti)) or some other block that would trigger the interface.

**Comment by Silfryi** [comment]
The realistic solar-based temperature is in and has been for a little while, and from what I remember TAN has been out of support for a while now so the only thing left to get from this issue is planet claiming.

**Comment by voidsong-dragonfly** [comment]
Last part of this issue is better served by #1895
