### ISSUE TITLE
Suggestion/idea: Crater improvements

### ISSUE THREAD

**Issue by Ithronyar** [Advanced-Rocketry/AdvancedRocketry#1234]
A terrain improvement that would make moon biomes more interesting and... well, more moon-like. Right now they have occasional moderately-sized craters, but actual moon-like environments are blanketed in craters of all sizes.

On the topic of craters: They look a little strange right now. Their rims have an obvious sharp ring jutting out of the landscape. Real crater edges tend to gradually level out with the surrounding landscape.

**Comment by voidsong-dragonfly** [comment]
Fixed in dev and will be coming soon, minus the extreme abundance of craters because there isn't a good way to show 1 or 2 block deep craters without being painful to the player, and those are the largest contingent of craters on moonlike bodies.
