### ISSUE TITLE
Suggestion: Restrict IO slots in All Machines

### ISSUE THREAD

**Issue by TotalHamman** [Advanced-Rocketry/AdvancedRocketry#1255]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.

## Have you verified this is an issue in the latest unstable build
Unsure, using build from Discord posted April 14 at 1:50 AM CDT

## Version of LibVulpes
 LibVulpes-1.12.2-0.2.8-29

## Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

## Crash report or log (if applicable)
No Crash

## Description of the problem
Suggestion to restrict data storage IO slots in all machines to the specific data type that is stored to buffer.  
Suggestion to restrict the stack size to one in the slots.  
Suggestion to add slot for empty data storage units to be moved when empty.  

These three combined should reduce if not outright resolve issue #1254 as well as help with the auto-insertion / removal of data storage units.

**Comment by voidsong-dragonfly** [comment]
Data hatches are now automatable, but are not data-locked, due to how it works. Fixed in 2.0.0
