### ISSUE TITLE
Ingame Manual

### ISSUE THREAD

**Issue by CTH999** [Advanced-Rocketry/AdvancedRocketry#1368]
I think it would help A lot if we had an ingame manual. However, that's just my thought!

**Comment by Jummit** [comment]
Maybe a multiblock structure that gives you tips, for example a mission control building?

**Comment by CTH999** [comment]
Tat would definatly be an interesting way to do a manual!

I like that Idea!

**Comment by voidsong-dragonfly** [comment]
Duplicate of #66
