### ISSUE TITLE
[Suggestion] Make ore mineable by laser drills defined per planet

### ISSUE THREAD

**Issue by wormzjl** [Advanced-Rocketry/AdvancedRocketry#1394]
Specifically laserDrillOres in the main config file
Currently it's the same for all planets, I think it's more reasonable to be defined in a manner like oreConfig.xml or planetDefs.xml

**Comment by slappav** [comment]
I disabled the laser drill in my pack. Would enable it again if this gets implemented.

**Comment by KyleBCox** [comment]
NOTE: 'voidmining' only not pulling ores from planet

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
