### ISSUE TITLE
Asteroid Mining - Thoughts and Suggestions

### ISSUE THREAD

**Issue by Golrith** [Advanced-Rocketry/AdvancedRocketry#1419]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-107-universal
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-39-universal
## Version of Minecraft
12.2.2

## Description of the problem
The progression of obtaining data to eventually launch a mining drill at an asteroid is quite backwards and very slow.

The method in earlier versions made much more sense and I'd recommend going back to that, with some minor improvements.

Start first with the observatory, this creates distance data, 10% chance of mass data, and 1% of composition data. (Observatories can calculate mass and get an idea of composition from just observing).
This is then transferred into the Astrobody Data Processor, from which using distance data allows you to select an asteroid, the more data used, the greater chance of asteroids located further away being shown.
The ADP pumps the data into the asteroid chip as normal.

Satellites are a launched to improve gaining mass and composition data,

Regarding data gain and transfer, it's very slow. Can you add a config option to control the rate of gain & transfer? The actual Mining Mission takes an amount of time (based on the number of mining drills), the slow data just turns it into an AFK waiting game.

At this moment in time in my modpack I'm debating on making a different way to obtain full data chips to bypass the satellite process, purely due to how slow it is.

**Comment by voidsong-dragonfly** [comment]
The next update should have data collection scale with satellite power, to a degree. However, the intended way for data production to increase is to launch multiple satellites. Launching 24 or 28 is a decent number, 8 of each or 8 of each + 4 extra distance.

**Comment by voidsong-dragonfly** [comment]
Data update was a part of 2.0.0, and as stated above, build multiple satellites. No one said you could only have 1 of each type.
