### ISSUE TITLE
[SUGGESTION] starships

### ISSUE THREAD

**Issue by Spacecoder22** [Advanced-Rocketry/AdvancedRocketry#1472]
So I have had this idea for a while now. A starship is built in the same way as an unmanned vehicle, but act in a similar sense to rockets. To take off, there needs to be a runway, which is created by placing a line of runway guide blocks on the sides of the runway. Once the ship reaches the end, the player takes control. Using WASD, you steer, and you can aim your ship upwards and downwards via the LCtrl and Space Keys. Your starship can be equipped with multiple modules, such as:
Targeting device: allows the player to focus turrets onto a specific target.
Cloaking device: makes the ship and player invisible to others, and also lodges ship signature transmission. (This comes in later)
Missile launchers: missile launchers launch missiles at specified target ships that are not using cloaking devices.

Escape pods (space station usage) on-the-fly space elevator for the most part. You will crash land on the planet you are orbiting, but nothing will happen if it’s a gas giant.
Even if one or two of these features is added, I think they’d be cool to have in game.

**Comment by voidsong-dragonfly** [comment]
Closed due to being moved to a central issue (#2036)
