### ISSUE TITLE
[SUGGESTION] planet icons

### ISSUE THREAD

**Issue by Archilyte** [Advanced-Rocketry/AdvancedRocketry#1520]
How about a RGB/HEX chosen custom planet icons, with overlays (like a RGB colored circle, with an RGB colored overlay that looks like a landmass on top of it)?
the icon is a square that is used in the spacestation skybox, but cut as a circle when viewed from a moon/planet destination selector

**Comment by voidsong-dragonfly** [comment]
You can provide your own (image) icons now.
