### ISSUE TITLE
[Suggestion] Have launching/landing rocket cause fires

### ISSUE THREAD

**Issue by scribbler957** [Advanced-Rocketry/AdvancedRocketry#1526]
Right now rockets can land on leaves (DW20's E2e ep 68) or take off next to wood and vanilla glass (my base) without any damage. I think some nice scorch marks and terrain damage would be in order. Until the anti-gravity update, we need to start building blast walls and such.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
