### ISSUE TITLE
[Suggestion] Texture the small plate press

### ISSUE THREAD

**Issue by scribbler957** [Advanced-Rocketry/AdvancedRocketry#1527]
Having the small plate press look exactly like a vanilla piston can be confusing. I ran the vanilla piston through some filters to try and make it look a little more metallic (like a piston coated with 3 iron). Since there's no texture to override I can't test it without forking and modifying it, etc. So, if you like, I'm glad. I might take a shot at the coal generator/furnace (maybe something with red veins or add the battery...)
![smallplatepress_top](https://user-images.githubusercontent.com/15851438/53538114-47155880-3b04-11e9-9efe-580d42f264fd.png)
![smallplatepress_inner](https://user-images.githubusercontent.com/15851438/53538116-47155880-3b04-11e9-8870-76312873d383.png)
![smallplatepress_bottom](https://user-images.githubusercontent.com/15851438/53538117-47155880-3b04-11e9-8390-d74cfcf5fc5b.png)
![smallplatepress_side](https://user-images.githubusercontent.com/15851438/53538119-47155880-3b04-11e9-9942-08bc732b4038.png)

If you like the idea, but it doesn't quite work, I'd be happy to mess with it once I can test it.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
