### ISSUE TITLE
[Suggestion] Portable rocket assembler.

### ISSUE THREAD

**Issue by Poxorosa** [Advanced-Rocketry/AdvancedRocketry#1528]
This item will give u ability to assemble rocket without launch pad and rocket assembler. When u rightclick  to the block, a red field will appear. U must cover rocket with this field and press "assemble" button, after that rocket will assemble. This item must be charged (100 000rf max) and will consume 50 000 rf for one assembling

**Comment by voidsong-dragonfly** [comment]
Not happening. Rocket assembly should take a large amount of infrastructure.
