### ISSUE TITLE
[Suggestion] spaceship.

### ISSUE THREAD

**Issue by Poxorosa** [Advanced-Rocketry/AdvancedRocketry#1530]
Spaceship is gonna be like space station, but smaller and will have ability to land on planets.
Spaceship controller block: this block will be a "heart" of the ship. This block allows to select planets, land on planets, take off planets.
Turrets: turrets will be a defender mechanism of the ship. Turrets will defend ship from the hostile mobs.
Planet scanner: this block will scan orbited planet and allows u to see planet landscape from the orbit and select place for landing.
Spaceship engine: this block needed to all spaceships. Fly time: 40 sec.
Ion thruster: faster version of spaceship engine, but this thruster needs nitrogen as a fuel. Fly time: 13 sec.
All this blocks require energy or fuel.
Landing stabilizer: when u landing, u have a chance to crash. Stabilizer block nullifyes this chance

**Comment by Silfryi** [comment]
The blocks of stations don’t move, it’s just a render. Making the blocks move, as you suggest, could cause crashes/other serious problems and corruption.

**Comment by Poxorosa** [comment]
> The blocks of stations don’t move, it’s just a render. Making the blocks move, as you suggest, could cause crashes/other serious problems and corruption.
Spaceship can be just teleporting to planet. Like in futurepack. U build ship and this ship teleporting to dimension.

**Comment by Silfryi** [comment]
The problem with having the blocks move _at all_ is some data may be location-specific, and the tile will be corrupted if it is moved, even teleported.

**Comment by voidsong-dragonfly** [comment]
Closed due to being moved to a central issue (#2036)
