### ISSUE TITLE
[Suggestion] Anti-Fog Visor Wearable/Enchantable/Bauble Ability

### ISSUE THREAD

**Issue by jaxmacky** [Advanced-Rocketry/AdvancedRocketry#1535]
Add an Anti-Fog Enchant that can be used on any helmets.

Add the ability to wear Anti-Fog Visor, stand alone.

Add the ability to use Anti-Fog Visor in a Bauble Slot.

Not all planets require Full Space Suit, yet still may have Fog.

**Comment by voidsong-dragonfly** [comment]
Not happening, as it ruins the reasons to actually wear an AR space suit.
