### ISSUE TITLE
[Suggestion] Satellite Builder

### ISSUE THREAD

**Issue by jaxmacky** [Advanced-Rocketry/AdvancedRocketry#1541]
AdvancedRocketry-1.12.2-1.5.0-132-universal.jar
LibVulpes-1.12.2-0.4.0-52-universal.jar
1.12.2 Minecraft

Why does the Satellite Builder require a Power Input Plug making it a Multiblock, where the  Rocket Assembly machine does not. To add further confusion, there is nothing in the Holo-Projector regarding the Satellite Builder Multiblock.

Suggestion is t o remove the requirement for the Power Input Plug on the Satellite Builder.

**Comment by MrEyeballs29** [comment]
And also have the power inside of the block

**Comment by CTH999** [comment]
I can't find how to make this multiblock. Bug? Stupidity (My part)?

**Comment by Jummit** [comment]
Put a power input plug under the machine for it to work.

**Comment by CTH999** [comment]
Thanks!

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0, it now is in the holoprojector.
