### ISSUE TITLE
[Suggestion] Coordinate selector.

### ISSUE THREAD

**Issue by Poxorosa** [Advanced-Rocketry/AdvancedRocketry#1551]
If coordinate selector is installed in the rocket, u can select coordinates for next landing on the planet. And randomize button. This button select random coordinates.

**Comment by ViciousGamer** [comment]
[Something like that already exists](http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/LandingPad.php)

**Comment by voidsong-dragonfly** [comment]
Yes, this niche is filled by the pad.
