### ISSUE TITLE
[Suggestion] Realism Increases

### ISSUE THREAD

**Issue by Silfryi** [Advanced-Rocketry/AdvancedRocketry#1555]
Some things in Advanced Rocketry make little sense and could be made a little better:

1. The airtight seal enchantment is applied in a chemical reactor with a diamond. This would not seal anything. It could possibly make the seal worse. I would suggest moving it to the precisison assembler with either a pipe seal or titanium sheets
2. Moon Turf is named moon turf. This only applies to soil on moons, but it could be generated on planets. If the name was changed to regolith, it would cover all soils of that type.
3. Crafting of circuits by hand needs diamonds. If it was changed to quartz, it would serve a similar function without having no IRL use in circuits.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
