### ISSUE TITLE
[Suggestion] - More custom icons.

### ISSUE THREAD

**Issue by Poxorosa** [Advanced-Rocketry/AdvancedRocketry#1557]
I want to suggest more icons for a planets.
Desertlike - desert planet icon.
Asteroid - asteroid icon.
Plasma - plasma icon.
Jupiterlike - Juipter icon.

**Comment by Silfryi** [comment]
... Plasma will never be on a planet. It’s either a star or it’s made of gas.

**Comment by C1ffisme** [comment]
I would say as a possible alternative to plasma, you could have a hot Jupiter/hot terrestrial planet heated to a glow by its proximity to the sun.

**Comment by voidsong-dragonfly** [comment]
All of these icons have been implemented other than plasma, which can be added as a custom one loaded from ResourceLoader if needed.
