### ISSUE TITLE
[Suggestion] More Suit Upgrade Ideas (some may have been said before)

### ISSUE THREAD

**Issue by portalfan04** [Advanced-Rocketry/AdvancedRocketry#1574]
I apologise if i've formatted this incorrectly, i've never used github before.

Add scuba gear to the suit to help on water planets. Gear may include the following:
Fins, for feet, crafted with silicon plating, makes the player swim faster but walk slower
Rebreather, for torso, crafted with advanced circuits and titanium, cycles air to result in less oxygen usage underwater
Helium Tank, fill a tank on a gas charge pad with helium, allows for even less water usage underwater
Anti **Vapour** mask, for helm, crafted with milk (for lack of a better resource), allows for better vision underwater
General Gear ideas i've had
Skin Suit (upgrade for the whole suit), crafted with lots of silicon plating and titanium plating, allows for better mobility everywhere. However, the suit will struggle in absolute vacuums and air will drain faster.
Biotic Arm Upgrade, for torso, crafted similar to leg, will increase tool speed and melee weapon damage.
Exoskeletal Suit, for whole suit, crafted with biotic arms and legs, will allow for a great increase in agility and strength.

Suit armour upgrades, will allow for greater suit durability. The suit armour upgrates will go into a slot specifically for them
Tier 1, making the suit as good as leather (unmodified suit will be scaled down significantly) and will be crafted with iron plates
Tier 2, making the suit as good as iron, will be crafted with diamond
Tier 3, making the suit as good as diamond, will be crafted with titanium

Rangefinder, for helm, crafted with circuits, will increase ranged weapons accuracy and projectiles velocity
Rocket Boots, for boots, crafted with 2 basic rockets, allows for double jumping
Wingsuit, for torso, crafted with silicon, adds an elytra
Infra Red/NV Goggles, both crafted with lenses and circuits, will allow for vision in night. Infra Red makes living enemies and heat sources extremely bright and vision obstructing.
Slot extender placable in a dedicated place for each suit piece, crafted with a bunch of titanium/iridium alloy, allows for more upgrade slots in the suit.

Please give feedback!

**Comment by Silfryi** [comment]
Why have double jump when you can just install a jetpack in the chestplate?

**Comment by voidsong-dragonfly** [comment]
This overall destroys the balancing of the space suit while trying to make it into a full modular suit of armor with high protection, and the rest of the suggestions can be done with other mods (colytra, etc). Closing due to uncertain at best implementability.
