### ISSUE TITLE
[Request] Make the "be the first to" advancements hidden

### ISSUE THREAD

**Issue by Lykrast** [Advanced-Rocketry/AdvancedRocketry#1577]
Since only realistically one person can get this advancement on a server, and in single player those don't matter, it would be really nice to make them hidden advancements (like a few vanilla has). This will stop them from taunting people in the advancement pages as they will never be completable if someone already claimed them.

**Comment by voidsong-dragonfly** [comment]
Completed for next 1.16 release.
