### ISSUE TITLE
Flan's Mod planes can access Planet Selection GUI[Request]

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1583]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]
Basically how this would work is if a specific Flan's Mod plane had a line in it that said "IsSpaceship True" then flying up to Y 1000 with that plane and having a guidance computer and some Dilithium in the cargo bay would allow the plane to fly to other planets and/or space stations.
This would require a hook, but I think this is actually a very good idea since it would make all the spaceships that me and other people have made actually able to fly to space.

**Comment by voidsong-dragonfly** [comment]
We will not be adding Flans compat for their planes as they could significantly usurp AR rockets, and why would we invalidate large parts of the mod? They also would possibly become immune to balancing decisions we make in the future. We _do_ have API calls for some things, but direct Flans compat is not happening.
