### ISSUE TITLE
[sugestion] meteors on space stations

### ISSUE THREAD

**Issue by QuintenMC** [Advanced-Rocketry/AdvancedRocketry#1585]
Meteor strikes.
On a space station a rare meteor hit event might happen. 
This can be stopped using a meteor shield or when repaired before phase 3 using a new repair tool.
When the impact reaches phase 3 the only escape are escape pods rockets won't work and the station is doomed. When an escape pod is launched it will search for an escape pod beacon and try to land nearby one.
However if there is no beacon on the planet the station was orbiting it will land near the spawn point.
I also thought about gas giants. When the station is orbiting a gas giant it will search for a near moon if no moon is found it will float in orbit until rescue or dead. 
If no rescue takes place the player will probably starve. But upon respawn the player will get an pod id chip to put into a rescue rocket this rocket will pickup the items if provided by a chest (or 2 if you have a full inventory)
Now the phases
Phase 1: Alarm, when having the alarm system it will make an alarming sound and the screen edges will flash red. With the right upgrade this system will also make an X where the meteor hit so the player can repair it.
Phase 2: Power outage: All power will get killed no matter the source, this means no gravity control or oxygen.
Phase 3: meltdown only escape pods work and the station will start to heat putting flamable blocks on fire and making water dissapear. The station is also doomed from now on.
Phase 4: Total explosion. killing and breaking everything on the station.

**Comment by MrEyeballs29** [comment]
In real life the chance of getting a meteor hit is lower than 10^-6 percent.

**Comment by QuintenMC** [comment]
i never said it had to be realistic just thought it would be a cool adition

**Comment by MrEyeballs29** [comment]
Well for every 24000 seconds yes

**Comment by Silfryi** [comment]
This will likely go into the hardmode update.

**Comment by voidsong-dragonfly** [comment]
Duplicate of #386
