### ISSUE TITLE
[REQUEST] Flying Mobs Should be able to ignore gravity

### ISSUE THREAD

**Issue by CaptainStalfoss** [Advanced-Rocketry/AdvancedRocketry#1665]
As you may know, Any flying mobs or even Chickens, Will float into space if the gravity is to low, Or if its to high they will get pushed into the ground.

I suggest (if at all possible) having a config option that lets certain Mobs ignore gravity, (aka act as if its in normal earth gravity).
Not only would this fix the issue, It would also be useful to make certain space mobs less floaty.

If its not directly possible, Maybe there's a way to Add/remove gravity to the specific mob.
If planet has gravity of 50, then The mob could get 50 extra gravity.
Not sure how this all works, i'm just doing guess work.

(Not sure why the title said bug before, but i changed it)

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0, `EntityFlying` no longer has gravity affect it.
