### ISSUE TITLE
advanced force field projector

### ISSUE THREAD

**Issue by Nethet** [Advanced-Rocketry/AdvancedRocketry#1680]
I want an advanced force field projector which do a sphere made out of force fields around it.
It consumes energy, Forge energy, (not like the normal force fields) and the size of the sphere, or oval, or cube is 100% modulable. It have to be hard to craft (so the peoples use the normal force field projectors and don't forget them). And when you sneek you can get out of the sphere but not in (so the player have to do a teleporter system in his base or a redstone code, or he just activates it when he is attacked). The foce fields replace just air blocks.
I know there are other mods who add this but in every sci-fi serie there is this things and I think your mod is very sci-fi _(this isn't an argument)_.
Keep the old force field projector to make bridges please.

Thank you in advance for an awnser.

**Comment by NutMaster6942** [comment]
Making it use only forge energy would be impossible as most mods can either: swap power types or accept all power types.

**Comment by Nethet** [comment]
but forge energy is universal

**Comment by NutMaster6942** [comment]
That's why it's impossible for it to only use FE.

**Comment by Nethet** [comment]
ok if u say so

**Comment by voidsong-dragonfly** [comment]
Just use RFTools for this, its system will consistently outperform anything we could come up with.
