### ISSUE TITLE
Minecraft Vanilla style planets with phases[Request]

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1695]
I hate the new stars and planets because they look too realistic for Minecraft.
Can you please change the planets to these?
They all have phases and there's one image per planet type as well as a base template you can make your own planets with.

 This is a Stormlands planet:
![stormlandsplanet](https://user-images.githubusercontent.com/11968498/64551831-fc229c00-d303-11e9-9a73-5a8f5fde9e9e.png)
Swamp planet:
![swamp](https://user-images.githubusercontent.com/11968498/64551833-fcbb3280-d303-11e9-9819-6ccfd63a4c69.png)
Water Planet:
![waterworld](https://user-images.githubusercontent.com/11968498/64551834-fcbb3280-d303-11e9-9713-cbc7d75e29d4.png)
Base tempate:
![base](https://user-images.githubusercontent.com/11968498/64551835-fcbb3280-d303-11e9-8dd9-cd6b575560e4.png)
Desert Planet:
![desert](https://user-images.githubusercontent.com/11968498/64551836-fcbb3280-d303-11e9-987c-8a5443539481.png)
Earth-specific icon:
![earth](https://user-images.githubusercontent.com/11968498/64551837-fd53c900-d303-11e9-97f5-9d871ac1fd8a.png)
Earthlike planet:
![earthlike](https://user-images.githubusercontent.com/11968498/64551838-fd53c900-d303-11e9-89e1-f68c09863c0a.png)
Forest, Jungle, warm taiga, or mega taiga planet:
![forest_jungle](https://user-images.githubusercontent.com/11968498/64551840-fd53c900-d303-11e9-8143-871cb35d0388.png)
Ice planet:
![iceworld](https://user-images.githubusercontent.com/11968498/64551841-fd53c900-d303-11e9-9daf-7894777431a3.png)
Lava planet:
![lava](https://user-images.githubusercontent.com/11968498/64551842-fdec5f80-d303-11e9-8e29-707fa10a4fda.png)
Mars-like planet:
![marslike_phases](https://user-images.githubusercontent.com/11968498/64551843-fdec5f80-d303-11e9-9ec9-ab2b4cbedc11.png)
Moon-like planet or moon:
![moon_phases](https://user-images.githubusercontent.com/11968498/64551844-fdec5f80-d303-11e9-81db-c32489ec62e5.png)
Highly polluted toxic planet:
![orxonian](https://user-images.githubusercontent.com/11968498/64551845-fdec5f80-d303-11e9-8fc6-0484cb4f77f4.png)
I'd also like the suns to be returned back to the vanilla Minecraft style suns.
They're too realistic and it hits right in the asscrack of  the uncanny valley for me.
I love your mod though and I suppose that for now I could make a resource pack to change them to these until (And if) they get implemented.
 

**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]

**Comment by TripTripy** [comment]
I feel like this should be a config option instead of a strait out change, because people's opinions will change

**Comment by AGiLE-EaGLE1994** [comment]
As long as it gets added, I don't care if it's a config option or default. c:

**Comment by AGiLE-EaGLE1994** [comment]
![gasgiantorange](https://user-images.githubusercontent.com/11968498/64704738-c2c16c00-d47c-11e9-8395-b56c50adf815.png)
![gasgiantblue](https://user-images.githubusercontent.com/11968498/64704739-c2c16c00-d47c-11e9-8d6c-3eb014da32a2.png)
New Gas Giant sprites

**Comment by AGiLE-EaGLE1994** [comment]
thanks! C:

**Comment by Gliese-832-c** [comment]
Maybe also more gas giants, like yellow, green, dark blue, pink, purple, beige. Here is an inspiration: https://imgur.com/a/Ip9m3PO

**Comment by voidsong-dragonfly** [comment]
Planet textures were already scaled down to be the same size as stars (128x) in 2.0.0 or the directly proceeding updates. We have no plans to go lower at the current time, as the current scale is both significantly more MC-like and still round..
