### ISSUE TITLE
Alien and spaceship mobs?[Request]

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1700]
Is it possible you could add alien animals, villagers, stations, rockets and shuttles that would populate planets with alien biomes or Galacticraft dim-mapped planets or moons?
There could also be spaceship mobs that you could encounter in the asteroids dimensions or in warp that would attack you and you would have to shoot at them with lasers or other weapons, and if you shoot them down you can use the tractor beam to obtain a box containing all of their loot.
But there could also be friendly ships and combat events where a friendly or neutral ship is being attacked by a hostile ship and you have the option to help the friendly ship defend itself.
The alien animals would be analogous to the vanilla Minecraft mobs, and you'd have 3 different versions of each, and the species would be the following: Alien cow, alien chicken, alien pig, alien wolf, alien ocelot, alien horse, hover horse, alien slime, alien creeper, rocket creeper.
there'd be 3 different subtypes of each of these mobs which would spawn on different types of planets, for example you could have a cold climate version of them, a warm climate version, and a temperate version. AR is a nice mod but I feel it needs a little help since it seems rather empty, which, while definitely realistic, means there's not quite as much fun as there could be exploring space, considering every planet with life is probably going to be identical to environments found on Earth unless it uses biomes from other mods.
These ship mobs and such would be encountered in asteroids dimensions (Not just AR ones, but Galacticraft ones as well), in space stations (Rarely), and when warping to other planets. Every time you warp, you have a 1/24 chance to run into a ship of some type and 1/64 chance to run into a battle between two other ships or more.
It's also possible the alien villagers could have rockets of their own, or at least launch pads in their villages. If possible they might be able to actually USE rockets.
This feature is not one I want very badly, but I still thought it would be a good idea to suggest.

**Comment by NutMaster6942** [comment]
It sounds decently interesting, but needs some work.

**Comment by AGiLE-EaGLE1994** [comment]
As an update: The hover horses would be able to go over water, cobwebs, lava, unsupported/flying sand or gravel, fire, cacti or any other surface that causes damage upon touching, and do it without them getting hurt. They could also fly over gaps if you hold the space button, and they'd have a limited amount of stamina for hovering over gaps, after which they would slowly glide down to the nearest ground.  Hover horses could also live on airless planets if you have such a planet that has structures enabled, and you could find alien villagers with stables which contain hover horses. The hover horses could be given iron, gold, diamond, or titanium armor, in addition to increasing their skin toughness by feeding them nuggets of that metal, and they could carry 2 large chests on their backs in addition to 2 passengers. Feeding a hover horse dilithium would increase its hover stamina and boost speed. Oh, yeah- that's another thing, hover horses can sort of "Sprint" by activating their afterburners. The afterburners would use up the hover stamina as well and would recharge slowly if the horse keeps "walking", but faster if the horse hovers in one spot, or even faster if it is fed redstone. Hover horses would have metal-armored skin and be immune to arrows, and could also have a slot in their inventory for station and planet ID chips to allow them to fly to a planet or station to meet you there, so they can go between worlds with you.
