### ISSUE TITLE
[Request] update the wiki pls

### ISSUE THREAD

**Issue by Archilyte** [Advanced-Rocketry/AdvancedRocketry#1703]
the [wiki](http://arwiki.dmodoomsirius.me/AdvancedRocketry/) is very outdated and lacks a lot of documentation...

a way to fix this is by letting volunteers edit and add on to the wiki

fyi last info of the wiki is for AR 1.4, now its AR 1.6

**Comment by Jummit** [comment]
see zmaster587/AdvancedRocketryDoc

**Comment by Archilyte** [comment]
but how do i know if any new features about [this](http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php) is added?

**Comment by dmodoomsirius** [comment]
Anything on there would be in the latest alpha in the game. Z updates that as its added to the game.

**Comment by Silfryi** [comment]
As well, that's just the changelog. Not necessarily the content-added log

**Comment by voidsong-dragonfly** [comment]
Wiki just got an enormous update.
