### ISSUE TITLE
More carbon collection cartridges

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1708]
A carbon collection cartridge currently lasts one real life day, as far as I know.

I would like to suggest a tiered system:
Advanced carbon collection cartridge - twice the durability, outputs 2 coal in the chemical reactor
Elite carbon collection cartridge - four times the durability, outputs 4 coal in the chemical reactor
Ultimate carbon collection cartridge - lasts an infinite amount of time, it should be very hard to craft, possibly using lots of iridium.

I just want to have an infinetly lasting creative mode/late game base/space station, so that would be a very awesome thing to see in the mod.

**Comment by Silfryi** [comment]
Automate it. I believe they can be extracted using pipes.

**Comment by Gliese-832-c** [comment]
@Silfryi This seems like a huuuuge pain in the behind to set up.

**Comment by Silfryi** [comment]
Not that bad if you've got decent pipes, and ender chests/some sort of teleportation of items is ubiqitous at this point. One to two ender chests, and you're good.

**Comment by Sarous** [comment]
Alternatively, oxygen vents accept redstone signals, much are much simpler to set up than item piping.

**Comment by voidsong-dragonfly** [comment]
Fixed (or, well, obsolete) by bed28e7d
