### ISSUE TITLE
Make the basic circuits from Advanced Rocketry be compatible with Mekanism and ICBM-Classic circuits.

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1709]
Like my dilithium compat suggestion, this should be really easy, just put circuitBasic into the oredictionary, and make the recipes accept circuitBasic. That way, you will be able to use Mekanism and ICBM-Clasic (possibly other mods) basic circuits.

**Comment by DDriggs00** [comment]
The advanced rocketry basic circuit is far more complex than the mekanism basic circuit, and I believe that it should not be oredictionaried

**Comment by voidsong-dragonfly** [comment]
As stated, the AR basic circuit is not like other mod's circuits - there is no real corollary between them.
