### ISSUE TITLE
Additional features when using Flan's Mod and AR  together [Request]

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1719]
Bonus features when you use Flan's Mod and AR together:
You can have a lander or rocket deploy a Flan's Mod ground vehicle or boat upon landing on a planet by putting it in the cargo of the rocket.
Flan's Mod planes can fly between planets and solar systems when they have a planet selector, dilithium, and warp core block in their inventory
When planes have "IsSpaceship True" in their config files, then they can fly between stars and planets with these items.
If they have a station ID chip, they can fly between stations that are on the same planet or one on the planet's moon and one orbiting the planet itself.
Flan's Mod Armor can allow you to breathe in space if  the line "SuppliesOxygen True" is in the config file for a piece of armor the player or entity is wearing

**Comment by TripTripy** [comment]
This sounds like a really cool request. I'd recommend posting it on Flan's Mod's github as well as this sounds like it would need work there as well.

**Comment by voidsong-dragonfly** [comment]
We will not be adding Flans compat for their planes as they could significantly usurp AR rockets, and why would we invalidate large parts of the mod? They also would possibly become immune to balancing decisions we make in the future. We _do_ have API calls for some things, but direct Flans compat is not happening.
