### ISSUE TITLE
[Request] Biome pressure Config

### ISSUE THREAD

**Issue by Heyo13579** [Advanced-Rocketry/AdvancedRocketry#1728]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]

Im currently working on a mod pack and id like to be able to set certain biomes to generate at set pressures 
Example:

Wastelands 50bar
plains 60bar
grasslands 75bar
forests 100bar

im not sure how easy this would be to implement but if it could be done then it would help my mod-pack by leaps and bounds! 
The config structure could look something like this:
{
biomeid:X
biomepmax:X
biomepmin:X
}

**Comment by Silfryi** [comment]
This is absolutely not how the pressure system works, and is not how it will work. Sorry! (Pressure is defined by dimension and now with temperatures factored in as well, it'd be nigh-on impossible to get a good, easy & realistic way to get this to work.)
