### ISSUE TITLE
[Request] starships

### ISSUE THREAD

**Issue by Eagle1128** [Advanced-Rocketry/AdvancedRocketry#1735]
Starships would function similarly to rockets but with their own special features. 
1. They are built using the same structure format as an unmanned rocket.
2. Instead of using fuel, the starship could probably use ion thrusters and dilithium/solar generators.
3. Starships May be too small to safely contain a warp core. In order to fix this, a hyper drive can be used. A simple 1x3x1 multiblock structure built on the starship. Due to hyper drives being very unstable and small, they can only hold 150 units of dilithium and must cool down.
4. If a starship has a warp controller, it can be linked to a warp core on a station. So using this feature, you can make stations with structures like the hyperspace docking rings in Star Wars for long distance travel.
5. When a starship takes off, it will need runway blocks which the starship will follow before flying upward to space, and will require runway blocks facing towards the docking pad to land.
6. You don’t need to warp to other planets in a starship. You can fly there normally, it will just take much longer.

Personally I think that this would be an amazing feature because starships would be interesting to use. Especially if they are expanded upon with like weapons or something. plus I REALLY wanna build a functional X-wing. Anyone else?

**Comment by Silfryi** [comment]
This is already somewhat implemented. You can put a warp core (the block, not multiblock) on a rocket, and then travel to other planets in the solar system.

**Comment by voidsong-dragonfly** [comment]
Closed due to being moved to a central issue (#2036)
