### ISSUE TITLE
[Request] Warp Controller on a Rocket ought to require dilithium

### ISSUE THREAD

**Issue by MuteTiefling** [Advanced-Rocketry/AdvancedRocketry#1749]
**What do you think is missing or what do you think can be done better**
I just recently even learned that the Warp Controller could be placed on a rocket to allow it to travel to other planets in the same solar system. But I was kind of surprised to learn that this didn't require any extra fuel or dilithium crystals. 

My suggestion would be to add an inventory to the rocket when the Warp Controller is present (similar to the one added by the Guidance Computer) that would allow you to insert dilithium crystals for the Warp Controller.

**Comment by Silfryi** [comment]
You can already get an inventory by adding chests/the like. It should probably just pull from there.

**Comment by MuteTiefling** [comment]
Nice!
