### ISSUE TITLE
[Request] Galacticraft + Extra Planets Support

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Advanced-Rocketry/AdvancedRocketry#1758]
I'm aware you can manually dimension map GC planets, but it would be really nice to have built in galacticraft support, or at least some official addon that does that.

Ideally, in a way where instead of AR using GC planets, GC uses AR planets, as AR planets are a lot nicer IMO.

**Comment by voidsong-dragonfly** [comment]
We are not overwriting GC planets. Dimmap and use AR as you said if you need that.
