### ISSUE TITLE
[Request] Rockets travel between planets

### ISSUE THREAD

**Issue by dkmk100** [Advanced-Rocketry/AdvancedRocketry#1798]
There should be a config option to allow a rocket with a high amount of fuel (maybe require advanced engines?) to be able to travel between different planets in the same star system, and only require the warp core for travel between different star systems. This would enhance the options a pack creator has for balancing purposes.

**Comment by Silfryi** [comment]
What do you mean? You can still gate warp without the core, by gating planet selection options like the holo planet selector and the warp core.
