### ISSUE TITLE
[Request] Make some fields, methods public / make public methods to access fields

### ISSUE THREAD

**Issue by slava110** [Advanced-Rocketry/AdvancedRocketry#1810]
Currently making OCRocketry addon and it would be awesome if you will make some fields, methods public or if you will make a way to access them:

**TilePlanetaryHologram**:
- [x] TilePlanetaryHologram#selectedPlanet
- [x] TilePlanetaryHologram#currentStar
- [x] Public methods to get/set size
_-----------------------------------_
- [x] Maybe something to prevent destination selection for warp controller with holographic planet selector. I mean, it's cool, but what if I don't want it to be set immediately? So... Any way to prevent it
_-----------------------------------_

**Altitude Controller** | **Gravity Controller** | **Orientation Controller** | **Big Gravity Controller**:
- [x]  Get current values and set target values

**TileSpaceElevator**:
- [x] Get capsule entity

**And any way to use**
- [x] **TileWarpShipMonitor**#meetsArtifactReq
- [x] **TileWarpShipMonitor**#getTravelCost
(maybe even make them static or move outside of their classes. As you wish)

_Sorry for any grammar mistakes, english isn't my native language_

**Comment by voidsong-dragonfly** [comment]
Now that the sides of the entity are exposed, is getting capsule entity even needed?
