### ISSUE TITLE
[Request] Configure geode contents in planet defs

### ISSUE THREAD

**Issue by MarkOfTheBeast** [Advanced-Rocketry/AdvancedRocketry#1819]
Instead of setting the geode contents in the main mod config, it would be better to be able to customize which ores we want appearing in geodes for each planet so that the contents of geodes can be customized for individual planets instead of all planets having virtually identical geodes.

**Comment by Gliese-832-c** [comment]
I totally agree, that will make the planets be much more diverse and unique and will make modpack authors' lives much easier.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
