### ISSUE TITLE
A config option to disable those wierd tanks that AR adds and just make it use buckets.

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1855]
They feel really out of place, it should just be normal buckets. If you want actual tanks, there's the pressurized ones from AR, and the Thermal Expansion reservoirs and portable tanks, and probably also many other tanks from mods that I forgot.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
