### ISSUE TITLE
a guide

### ISSUE THREAD

**Issue by fimzks** [Advanced-Rocketry/AdvancedRocketry#1861]
having a in-game detailed guide of the mod would be great explaining what coil is better isnt as clear as the motors also how the different pieces afect rockets would be a useful info as how to use satellites,observatories, unmaned vehicles, there are a lot of info that can be fit also it can be done in a progression way if the mod author likes to like thaumcraft does or not as far as it but step by step opening new branchs of knowledge

**Comment by voidsong-dragonfly** [comment]
Duplicate of #66
