### ISSUE TITLE
[Request] S:standardOres blacklist/whitelist toggle

### ISSUE THREAD

**Issue by storm37000** [Advanced-Rocketry/AdvancedRocketry#1883]
It would make it 1000x easier to make asteroids if i could set the `S:standardOres` to an empty blacklist so that there are no restrictions.  This is already done for the other lists in the config.  Also some ores without ore dict entries would be impossible in the current setup.

**Comment by Silfryi** [comment]
Asteroids IIRC do not use that list anymore. They use the asteroids.xml file instead, which _can_ take itemstacks. Plus, CraftTweaker can add to OreDictionary entries anyway.
