### ISSUE TITLE
[Request] Fix warp core's use of fuel

### ISSUE THREAD

**Issue by PyralIron** [Advanced-Rocketry/AdvancedRocketry#1894]
Currently the warp core will consume dilithium whenever the fuel value is below the fuel max, so no matter how much fuel a warp took, if there was any dilithium in the input slot, it would be consumed. I can see this not being a bug as you may _want_ it to consume fuel in order to have a max fuel value, in case certain warps take a near-max fuel cost. As a side note, the entire stack is consumed, not just one piece - this seems like a bug on its own.

However, I propose that you add a cap value to the fuel cost of any warp, and then make the warp core's fuel capacity be equal to the cap + the fuel value of one dilithium, and only make the core take in more dilithium when the fuel value is equal to or less than the fuel cap. Then, you will always be able to supply enough fuel for a warp, and dilithium will never be wasted.

**Comment by Silfryi** [comment]
Currently the warp core's fuel storage is equal to one warp + one dilithium (one dilithium is 500 and the max for a warp is 500). However, yes, that consumption is erroneous.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
