### ISSUE TITLE
[BUG] Z-fighting on Area Gravity Controller

### ISSUE THREAD

**Issue by aaronhowser1** [Advanced-Rocketry/AdvancedRocketry#1906]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12

## Description of the problem
https://cdn.discordapp.com/attachments/399708323722821643/748983505702224022/2020-08-28_14-12-27.mp4

**Comment by aaronhowser1** [comment]
yes it is

**Comment by aaronhowser1** [comment]
pls

**Comment by aaronhowser1** [comment]
yes it is

**Comment by aaronhowser1** [comment]
*github-actions please*

**Comment by Silfryi** [comment]
This'll get fixed whenever I give the thing a new model. Give it time

**Comment by aaronhowser1** [comment]
Probably

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
