### ISSUE TITLE
[BUG] Relogging on a space ship causes planets to spin wildly in the skybox

### ISSUE THREAD

**Issue by aaronhowser1** [Advanced-Rocketry/AdvancedRocketry#1911]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Crash report or log or visualVM (if applicable)
[debug.log](https://github.com/zmaster587/AdvancedRocketry/files/5183592/debug.log)
[latest.log](https://github.com/zmaster587/AdvancedRocketry/files/5183605/latest.log)
Both are too large for pastebin, sorry

## Description of the problem
If you relog while on a space ship in orbit, the planet will spin wildly. Tested by doing nothing but relogging. It doesn't get fixed by warping, or by leaving the station and coming back.
[Video](https://cdn.discordapp.com/attachments/399708323722821643/752536401807016084/2020-09-07_09-29-30.mp4)

**Comment by aaronhowser1** [comment]
Yes

**Comment by aaronhowser1** [comment]
Yes it is. Stalebot I will stab you in the face.

**Comment by MrEyeballs29** [comment]
Don't do that. It is doing its job and since due to lack of activity of the
devs, the issues will not be fixed.

**Comment by Silfryi** [comment]
[AdvancedRocketry-1.12.2-1.7.0-universal.zip](https://github.com/zmaster587/AdvancedRocketry/files/5840306/AdvancedRocketry-1.12.2-1.7.0-universal.zip)
Here's a build with a possible fix - it's likely to reset some things to default on update but they can be interacted with to reset. Does the issue still happen wit this build?

**Comment by aaronhowser1** [comment]
Nope, it works perfectly fine using that

**Comment by Silfryi** [comment]
Great! I fixed some other major issues in the process too, which is nice - it turns out this was appearing as a SP bug too but in a much more.... mundane form. SP, same as MP, didn't persist states, so it just went down to min but never spun like crazy as it did for server.

**Comment by aaronhowser1** [comment]
I never tried in multiplayer, all of this was in singleplayer. Glad you figured it out though!

**Comment by Silfryi** [comment]
For some reason I thought it was MP then. :P Either way, the problem's fixed now and the area has extra sanity checking so it shouldn't be able to come up again in any form. Plus the station's now the one storing the targets and not the controller (controller still increases, though), so settings persist across controllers being broken by mistake, which is a nice bonus.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
