### ISSUE TITLE
Performance issue with liquid conduits and reactor

### ISSUE THREAD

**Issue by Sir-Will** [Advanced-Rocketry/AdvancedRocketry#1915]
If a conduit is filling the reactor the inventory updated is being run too often causing performance issues.

![](https://i.imgur.com/cJYsfsV.png)
![](https://i.imgur.com/YcMGW7M.png)

**Comment by Sir-Will** [comment]
up

**Comment by Sir-Will** [comment]
up

**Comment by voidsong-dragonfly** [comment]
If I had to guess, the reason that this is taking a while is that the recipe list is extensively long - can you give a report on how long it takes in a pack with fewer armors?

**Comment by voidsong-dragonfly** [comment]
Duplicate of #1595
