### ISSUE TITLE
Possible Infinite Write Loop In Planets

### ISSUE THREAD

**Issue by PercyJames** [Advanced-Rocketry/AdvancedRocketry#1928]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/QNAh8Vrp

## Description of the problem
ok, i try to join my test worlds but this happens.

**Comment by MrEyeballs29** [comment]
That might be an infinite loop. What on earth did you do?

**Comment by PercyJames** [comment]
https://pastebin.com/9UDwvKcz

**Comment by PercyJames** [comment]
hello?

**Comment by PercyJames** [comment]
i gave a pastebin of my XML

**Comment by PercyJames** [comment]
it has been nearly two days.

**Comment by PercyJames** [comment]
you're no help at all.

**Comment by PercyJames** [comment]
i will copy paste this issue until i get answers.

**Comment by MrEyeballs29** [comment]
Would you stop reopening and closing.

**Comment by PercyJames** [comment]
gladly.

**Comment by PercyJames** [comment]
i'm getting no help for this issue.

**Comment by MrEyeballs29** [comment]
You put a space on line number 581. `<planet name="Formido" DIMID=" -1013" dimMapping="" customIcon="moon">`

**Comment by dmodoomsirius** [comment]
ok here is where i lock the issue. Learn patience. People are busy and are busy with real life. there are issues on here that are much older then yours and we have not been able to get to. So I will leave this issue locked for now with no eta on unlocking it. I get that is has been a bit. but you will not spam closing and opening the issue trying to get attention.

**Comment by voidsong-dragonfly** [comment]
Likely user error. Old version.
