### ISSUE TITLE
[BUG] Cannot drag UI

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [Advanced-Rocketry/AdvancedRocketry#1932]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal
I originally found the bug on version AdvancedRocketry-1.12.2-1.4.1-120-universal, and found it still happens in the lastet version.

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal
I originally found the bug on version LibVulpes-1.12.2-0.3.0-45-universal, and found it still happens in the lastet version.

## Version of Minecraft
1.12.2-forge1.12.2-14.23.5.2838

## Does this occur without other mods installed
Yes (I tested both in a custom modpack and with just LibVulpes and Advanced Rocketry)

## Description of the problem
With the lock UI set to false in config, it says you're supposed to be able to drag UI (like the space suit and oxygen tank UI) when the chat is open. When I do this, nothing happens (and yes I'm sure I have lockUI set to false).

**Comment by BabyGrootTheEpic** [comment]
Yes, I just tested again with AdvancedRocketry-1.12.2-1.7.0-235-universal & LibVulpes-1.12.2-0.4.2-75-universal, and the bug is still the same.

**Comment by voidsong-dragonfly** [comment]
Sadly we lost our hook for this at some point.
