### ISSUE TITLE
[Request] Config Option to make an existing Dimension require Oxygen

### ISSUE THREAD

**Issue by Shattered2909** [Advanced-Rocketry/AdvancedRocketry#1938]
I have been looking for some ideas to make the Nether more dangerous in my pack, got the idea to make it require Oxygen from AR because of the toxic gases in that Dimension.

It would be nice if AR had a config list for Dims that also need Oxygen? Would give pack devs the opportunity to make the Oxygen system relevant and useful before getting into Space.

**Comment by Archilyte** [comment]
can't you already do that in the planet list configs?

**Comment by Shattered2909** [comment]
Maybe, but wouldn't that add the Nether to the Planets one can fly to?

**Comment by Archilyte** [comment]
yes it would, but make it so that you can only discover it once you research an artifact item, and make said item uncraftable.

**Comment by Shattered2909** [comment]
Wouldn't that kill all the mobs though?

**Comment by Archilyte** [comment]
idk how to fix that

**Comment by Shattered2909** [comment]
Do you know if it would?

**Comment by Archilyte** [comment]
when i played with this mod, it did. idk if it does now

**Comment by voidsong-dragonfly** [comment]
You cannot assign an atmosphere without having the dimension be accessible to AR, somehow. You can, however, make the mobs there immune with the config.
