### ISSUE TITLE
[BUG] Binary Stars reset to being identical after world reload

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1944]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>[AdvancedRocketry-1.12.2-1.7.0-235-universal

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [] N
- [] N/A

## Version of LibVulpes
>[LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>[1.12.2, Forge 14.23.5.2838

## Does this occur without other mods installed
- [x] Y
(Also occurs WITH other mods installed.) 
>If Y, what is the MINIMUM set of mods required.
Forge, Advanced Rocketry, LibVupes, of the specified versions

## Description of the problem
>{ Create a planetDefs.xml file in the world's advRocketry folder, and give any star in it a binary companion  (Or more than one, as long as there's AT LEAST one), and make the stars different sizes, temperatures, or separations from the parent star. View the system in a planet selector and it should look correct. Close the world and return to the title screen, and then re-open the world, check the planet selector, and now all of the stars will be identical to the parent star, all with 5,0 separation.  I've attached a planet defs file and some screenshots.
First screenshot: Mod list.
Second screenshot: The world after reloading.
Third screenshot: the world before reloading.
[planetDefs.txt](https://github.com/zmaster587/AdvancedRocketry/files/5425290/planetDefs.txt)
![ModList](https://user-images.githubusercontent.com/11968498/96921325-53d68500-147c-11eb-939c-313751cdbebe.png)
![AfterReload](https://user-images.githubusercontent.com/11968498/96921329-546f1b80-147c-11eb-8354-b4fd4ef3f164.png)
![BeforeReload](https://user-images.githubusercontent.com/11968498/96921331-546f1b80-147c-11eb-987c-67474709d322.png)

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
