### ISSUE TITLE
[BUG] Gas collector rocket Language Bug

### ISSUE THREAD

**Issue by Jannik24** [Advanced-Rocketry/AdvancedRocketry#1946]
## Version of Advanced Rocketry
>AdvancedRocketry 1.12.2-1.7.0-235 build -235 for 1.12.2
timestamp 25.10.2020 this is the newest

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes 1.12.2-0.4.2-75 build -75 for 1.12.2 

## Version of Minecraft
>Minecraft 1.12.2

## Does this occur without other mods installed
- [x] N/A

## Crash report or log or visualVM (if applicable)
>No Crash

## Description of the problem
>if i set the language to german it appears a button in the gas collector rocket that should not be there

English
![Minecraft 1 12 2 25 10 2020 18_41_54](https://user-images.githubusercontent.com/37809734/97115483-4678ff00-16f7-11eb-8dad-d8d12587fd39.png)

German
![Minecraft 1 12 2 25 10 2020 18_40_10](https://user-images.githubusercontent.com/37809734/97115694-580ed680-16f8-11eb-9c6a-579168205587.png)

**Comment by Jannik24** [comment]
yes still an issue

**Comment by Silfryi** [comment]
@Jannik24 can you try [this](https://www.dropbox.com/s/la0ntlz3c0p3j1j/AdvancedRocketry-1.12.2-1.7.0-universal_gascollectionfix.jar?dl=0) build for me? It _should_ fix your issue.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
