### ISSUE TITLE
[Request] Allow moons/planets to have retrograde orbits.

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1953]
The title, basically, I'm trying to recreate Triton, a moon of neptune that orbits the planet retrogradely.

**Comment by Gliese-832-c** [comment]
Could be done by giving it a negative orbital distance value maybe?

**Comment by Gliese-832-c** [comment]
Thinking of it, instead of being a boolean, it should probably be done using an orbital inclination value. Though implementing the skybox for that might be very hard...

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0, with a boolean for retrograde
