### ISSUE TITLE
[BUG] Planets aren't visible in the Warp Controller on servers, but they are on sp

### ISSUE THREAD

**Issue by aaronhowser1** [Advanced-Rocketry/AdvancedRocketry#1955]
FTBTeam/FTB-University/issues/202
## Version of Advanced Rocketry
`AdvancedRocketry-1.12.2-1.7.0-235-universal`

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
`LibVulpes-1.12.2-0.4.2-75-universal`

## Version of Minecraft
1.12

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Description of the problem
FTBTeam/FTB-University/issues/202
![](https://user-images.githubusercontent.com/1723831/99190618-c713a400-2767-11eb-8db0-ac77135d17ec.png)
Planets aren't visible in the Warp Controller, despite isKnown being set to true. This *only* happens in servers.
Current workaround people are having to use is using the Holographic thing
![](https://cdn.discordapp.com/attachments/767004467974504448/779066677601370112/unknown.png)

**Comment by Consumerx54** [comment]
I am running a server of FTB University also and no matter how many times I load the 3 types of data into the warp controller it would not discover a planet.. Tried about 40 times then I went into the server advanced rocketry confic and set it so no need to discover and restarted server then I was able to see all the planets.  Getting there was another big problem but I understand this is the beta version so I won't list the many problems and crashes and wait for an update

**Comment by aaronhowser1** [comment]
Yes

**Comment by aaronhowser1** [comment]
yes

**Comment by voidsong-dragonfly** [comment]
Oi @aaronhowser1 I fixed a different bug with artifacts and server loading, do you mind seeing if it fixes this? I don't totally expect it to, but who knows, it might. (edit for clarity: the needed AR and LV versions are in the zip)
[output.zip](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6678347/output.zip)

**Comment by aaronhowser1** [comment]
Hm, I don't have a server running the pack atm. I suppose I could make one real quick and just try this, though.

**Comment by voidsong-dragonfly** [comment]
If you could, thank you!

**Comment by aaronhowser1** [comment]
Got a crash, but from WrapUp, the lib for JAOPCA: https://pastebin.com/PCv7zrDW

I guess I'll try removing those, should I forward this to the WrapUp issue tracker?

**Comment by voidsong-dragonfly** [comment]
Update JAOPCA, we changed some stuff, then they updated to fix it

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/122623340-4ac8a280-d061-11eb-8aa5-18363ad70f2e.png)
Changed some stuff indeed :eyes: I'm gonna have to play around with this when it's fully out and update the quests in my pack

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/122623574-3d5fe800-d062-11eb-8d86-59b76d050049.png)
seems to work fine for me
![image](https://user-images.githubusercontent.com/15698722/122623577-42249c00-d062-11eb-9a4d-a8b602868d06.png)
proof its on server

**Comment by voidsong-dragonfly** [comment]
Holy hell it actually _worked_?!?!?!

**Comment by aaronhowser1** [comment]
:tada:

**Comment by aaronhowser1** [comment]
What was the fix, if you didn't expect it to actually work?

**Comment by voidsong-dragonfly** [comment]
Artifacts didn't sync to NBT correctly.....

**Comment by voidsong-dragonfly** [comment]
So what I guess happened is they didn't sync to NBT so weren't sent to clients so no planets _could_ show because they all had no artifacts.

**Comment by voidsong-dragonfly** [comment]
Fixed with 2.1.0
