### ISSUE TITLE
[BUG] Rocket Loader and Unloader Have Swapped Item Textures

### ISSUE THREAD

**Issue by Trainerredstone7** [Advanced-Rocketry/AdvancedRocketry#1956]
## Version of Advanced Rocketry
1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
1.12.2-0.4.2-75

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A
>If Y, what is the MINIMUM set of mods required.

Just Advanced Rocketry and LibVulpes with the versions listed above, no other mods needed

## Crash report or log or visualVM (if applicable)
N/A

## Description of the problem
Rocket Loaders/Unloaders and Rocket Fluid Loaders/Unloaders have their item textures swapped. The item textures for the Loaders have orange markings and the textures for the Unloaders have blue markings, but when placed the Loader blocks have blue markings and the Unloader blocks have orange markings. I assume that the Loaders are supposed to be blue and the Unloaders are supposed to be orange.

**Comment by Silfryi** [comment]
Yes, they are, but this has stubbornly refused all attempts at a fix though it by all rights should be simple.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
