### ISSUE TITLE
Problems with the twilight forest mod and Advanced Rocketry

### ISSUE THREAD

**Issue by Nikkkkk4** [Advanced-Rocketry/AdvancedRocketry#1957]
## Version of Advanced Rocketry
 1.12.2-1.7.0-232
## Have you verified this is an issue in the latest unstable build
Y,N, N/A Y
## Version of LibVulpes
1.12.2-0.4.2-75
## Version of Minecraft
[insert here] 1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read

## Description of the problem
When going into the twilight dimension there is an oxygen problem when there shouldnt be one, i've see some other posts about it, but the solutions are complicated and I have no idea how to solve them, looking this issue up on youtube bring up no related searches.
[How can you reliably reproduce the problem]
Going into the twilight forest

**Comment by dmodoomsirius** [comment]
Make sure your planetDefs.xml does not have that dimension id dim mapped to the dimension that twilight forest. As that has been known to be the culprit.

**Comment by Nikkkkk4** [comment]
> 
> 
> Make sure your planetDefs.xml does not have that dimension id dim mapped to the dimension that twilight forest. As that has been known to be the culprit.
Do you have a youtube video showing how to fix it? If not can you be a bit more specific where I find these files and change them?

**Comment by dmodoomsirius** [comment]
inside your world folder you will find a planetdefs.xml. look at the config file for twilightForest in  the config folder look for its id. then change the Dim id in the Planetdefs.xml or add oxygen to that planet.
