### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HDL34** [Advanced-Rocketry/AdvancedRocketry#1961]
## Version of Advanced Rocketry
>[1.12.2-1.7.0-235

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>[1.12.2-0.4.2-75

## Version of Minecraft
>[1.12.2

## Does this occur without other mods installed
- [x] N

>[https://pastebin.com/U2RLqg6k

version of Forge: 1.12.2-14.23.5.2854

## Description of the problem
>[My modpack crashes when loading Advanced Rocketry at startup.

**Comment by Silfryi** [comment]
This is an unhelpful report, for we do not know why that occurs, as it's almost certainly a mod compat issue - can you find a minimum set of mods to that you can reproduce the crash with?

**Comment by HDL34** [comment]
Since then, I found the mod that caused the crash. It was an addon to Galacticraft "Interstellar exoplanet". I removed it (I was hardly using it) and managed to get your mod running.

**Comment by Silfryi** [comment]
Well, if it was not us, could you close the issue? We have no need of it, for it does not concern us.
