### ISSUE TITLE
The server crashed while creating the map

### ISSUE THREAD

**Issue by AtomBlood** [Advanced-Rocketry/AdvancedRocketry#1964]
## Version of Advanced Rocketry
1.12.2-1.7.0-235
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.4.2-75
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/tkR3N1Tt

## Description of the problem
Server version 1.12.2 CatServer-5068915.Crash when creating the map.

**Comment by Silfryi** [comment]
Is CatServer a non-Forge server software? If so, test in a plain Forge server environment. If it works there, we're unlikely at best to fix it.

**Comment by AtomBlood** [comment]
> CatServer是非Forge服务器软件吗？如果是这样，请在普通的Forge服务器环境中进行测试。如果它在那里工作，我们最多不可能修复它。

CatServer is 1.12.2 version Forge+Bukkit+Spigot server.https://github.com/Luohuayu/CatServer/blob/1.12.2/README_EN.md

**Comment by Silfryi** [comment]
Then we're unlikely to support it. Does it happen with a regular, plain-Forge server?

**Comment by voidsong-dragonfly** [comment]
We do not support non-Forge server software.
