### ISSUE TITLE
[BUG] Hovercraft death

### ISSUE THREAD

**Issue by MCSuperplayer** [Advanced-Rocketry/AdvancedRocketry#1967]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-235-universal.jar

## Have you verified this is an issue in the latest unstable build
No

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal.jar

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
N/A

## Description of the problem
>When reaching the ground with the hovercraft i instantly die even with padded landing boots equipped

Video of the Error: https://youtu.be/_t05KuKivME

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
