### ISSUE TITLE
[Request] New way to get power

### ISSUE THREAD

**Issue by mxnmnm** [Advanced-Rocketry/AdvancedRocketry#1989]
I know dyson spheres/swarms are out of the question, but I think it would be cool if there was a way to get power by orbiting a star. Maybe have a mechanic similar to collecting gas from gas giants only it is power from stars and have the collector ships require some kind of heat shield. The star type would impact the likelihood of your craft getting destroyed along with your rf quantity (which should def be configurable based on some set examples aka a star with these traits will produce x amount of power and have this likelihood of destroying the craft).

**Comment by Silfryi** [comment]
In the next few updates, microwave receivers will be able to work on stations. That's going to be the closest you'd get to this.

**Comment by dkmk100** [comment]
Why are dyson swarms out of the question? If satellites could be launched towards the sun and generate tons of power to transmit to other satellites, that would be super cool and I don't think it would be impossible to implement

**Comment by voidsong-dragonfly** [comment]
Because we already have solar satellites, and building a dyson swarm removes the (intentional) search for a good planet for solar - you're already given an automatic 'best' option.

**Comment by voidsong-dragonfly** [comment]
Microwave satellites have been updated to do this, and solar has also gotten another multiblock. This has been handled to the extent we will.
