### ISSUE TITLE
Stars always display black hole skybox

### ISSUE THREAD

**Issue by Shai444ko** [Advanced-Rocketry/AdvancedRocketry#1991]
## Version of Advanced Rocketry
>1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- N/A

## Version of LibVulpes
>0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- other mods do not affect this issue

## Description of the problem
>when you fly to the stars, they are all have black hole texture, no matter black hole this star or not

![2021-02-04_07 20 36](https://user-images.githubusercontent.com/68667665/106848483-bebd6c00-66b9-11eb-8f27-7b45b05f7bf9.png)
![2021-02-04_07 20 42](https://user-images.githubusercontent.com/68667665/106848486-bfee9900-66b9-11eb-9e94-a5ef05aa0b50.png)
![Screenshot_1](https://user-images.githubusercontent.com/68667665/106848685-16f46e00-66ba-11eb-9bb6-b692014035ad.png)

**Comment by Hibanka** [comment]
Same.

**Comment by dazadazu** [comment]
How do you get to the black hole?

**Comment by voidsong-dragonfly** [comment]
Old issue. Ask in the discord, don't necro old issues
