### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Philosyang** [Advanced-Rocketry/AdvancedRocketry#1993]
## Version of Advanced Rocketry
[AdvancedRocketry 1.12.2-1.7.0-232 build -232 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3015079)

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
[LibVulpes 1.12.2-0.4.2-75 build -75 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2949886)

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A

MINIMUM set of mods required:
- [forge 14.23.5.2854](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html)
- [LibVulpes 1.12.2-0.4.2-75 build -75 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2949886)
- [AdvancedRocketry 1.12.2-1.7.0-232 build -232 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3015079)

## Description of the problem
A stack of Data Storage Units can be placed into the IO slots in the Data tab of the Warp Controller, allowing a survival mode player to duplicate data.

1. Get some kind of satellite into the sky
2. Put some data into the Data Storage Unit with the Satellite Terminal
3. Store the data into the buffer of the Warp Controller with the Data Storage Unit
4. Craft some new Data Storage Units, for example, 4 Data Storage Units
5. Put these 4 Data Storage Units into one IO slot in the Data tab of the Warp Controller
6. Click "Store to Chip"
7. The player now can un-stack the Data Storage Units, with each of them having the original amount of data buffer.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
