### ISSUE TITLE
ProjectE Support

### ISSUE THREAD

**Issue by ParasiticSquid** [Advanced-Rocketry/AdvancedRocketry#1997]
Titanium and other items don't have EMC values when they logically should with projecte installed, maybe even the machines crafting recipes being able to properly calculate the resulting outputs EMC value.

That's pretty much it

**Comment by voidsong-dragonfly** [comment]
No use on this from us, lots of work for little gin and ProjectE is not a well-balanced mod anyway. No drive, no use.
