### ISSUE TITLE
(Suggestion) For convinience

### ISSUE THREAD

**Issue by DevTimur** [Advanced-Rocketry/AdvancedRocketry#206]
Make every Satelite chip showing satelites data.
For example it will show How much power it generate, and how much power storage it got. If that`s Microwave satelite, or how much data it collected, if it is data satelite. (I know it show this data in Satelite terminal, but i did not saw Solar production data in terminal, only text "Collecting energy", not actual ammount of energy it collects.)

Make so machines slots do not accept inapropriate items with shift click. and you can not put random items in (for example) satelite assembler slots, and if you shift click in assembler, it put item only in apropriate slot.

Maybe make Hint/Help buttons explaining how machine works, and what items it accepts.

Make so clicking Holo projector button close GUI and say something like "Click on ground" in chat.
Or maybe show text explaining what machine do, and button "Build" to confirm Holo projection choise.

Make so Data cable looks more cool. do not make this green cubes on cable every block, make them only on junctions, and next to data ports.
Make so rightclicking on this green cube, on data cable, TOGGLE it`s state from "Export" to "Import" and back, so you can use redstone singal OR rightclick to determine Data cable import/export state. (Maybe show little arrows on cube?)

That`s all suggestions i got for now, (I`m not gona talk about textures right now, maybe you should outsource textures to someone else?)

I`m not asking to implement this suggestions ASAP, but consider to use some of them, maybe.
P.S. I like this mod much more then GalactiCraft.

**Comment by voidsong-dragonfly** [comment]
Data cables have been replaced with wireless transceivers, scanning the entire recipe list for items from a machine is a bad idea for hatches performance-wise, hint/help buttons aren't useful with JEI and no item accepting buttons, satellites now actually do display correct data on the satellite, however this doesn't make sense to put on the chip as it's just a positional indicator. Holoprojector is better-organized and fairly self-explanatory now.
