### ISSUE TITLE
Oxygen crashes[BUG]

### ISSUE THREAD

**Issue by BraveCaperCat** [Advanced-Rocketry/AdvancedRocketry#2294]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.7.0.-232

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>0.4.2.-88

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Crash report or log or visualVM (if applicable)
>[---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  MixinBooter (.mixinbooter-4.1.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  OpenDisksUnpack (OpenDisks-MC1.12.2-0.1.0.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/26/22 12:13 PM
Description: Updating screen events

java.lang.NoSuchMethodError: zmaster587.libVulpes.util.FluidUtils.attemptDrainContainerIInv(Lzmaster587/libVulpes/util/EmbeddedInventory;Lnet/minecraftforge/fluids/IFluidTank;Lnet/minecraft/item/ItemStack;II)Z
	at zmaster587.advancedRocketry.tile.oxygen.TileOxygenVent.func_70299_a(TileOxygenVent.java:394)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at zmaster587.advancedRocketry.tile.oxygen.TileOxygenVent.func_70299_a(TileOxygenVent.java:394)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: zmaster587.libVulpes.inventory.GuiModular

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['BraveCaperCat'/254, l='MpServer', x=-1512.01, y=131.70, z=-1496.90]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 07 - Space, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-196,64,256), Chunk: (at 12,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1501185 game time, 13000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityRocket['Rocket'/253, l='MpServer', x=-1535.50, y=129.00, z=-1535.50], GCEntityClientPlayerMP['BraveCaperCat'/254, l='MpServer', x=-1512.01, y=131.70, z=-1496.90]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3557081528 bytes (3392 MB) / 5512364032 bytes (5257 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version               | Source                                          | Signature                                |
	|:------ |:------------------------ |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2                | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                      | 9.42                  | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                      | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore     | 1                     | minecraft.jar                                   | None                                     |
	| LCHIJA | micdoodlecore            |                       | minecraft.jar                                   | None                                     |
	| LCHIJA | mixinbooter              | 4.1                   | minecraft.jar                                   | None                                     |
	| LCHIJA | opencomputers|core       | 1.7.5.192             | minecraft.jar                                   | None                                     |
	| LCHIJA | fermion.asm.service      | 1.0.2+hotfix          | minecraft.jar                                   | None                                     |
	| LCHIJA | fermion.asm              | 1.0.2+hotfix          | minecraft.jar                                   | None                                     |
	| LCHIJA | bcrf.asm                 | 1.0.0                 | minecraft.jar                                   | None                                     |
	| LCHIJA | buildcraftlib            | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcore           | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftfactory        | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcrafttransport      | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftsilicon        | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | additionalpipes          | 6.0.0.8               | additionalpipes-6.0.0.8.jar                     | None                                     |
	| LCHIJA | libvulpes                | 0.4.2.-88             | LibVulpes-1.12.2-0.4.2-88-universal.jar         | None                                     |
	| LCHIJA | advancedrocketry         | 1.7.0.-232            | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | ctm                      | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHIJA | jei                      | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJA | chisel                   | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCHIJA | tconstruct               | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHIJA | galacticraftcore         | 4.0.2.280             | GalacticraftCore-1.12.2-4.0.2.280.jar           | None                                     |
	| LCHIJA | galacticraftplanets      | 4.0.2.280             | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None                                     |
	| LCHIJA | asmodeuscore             | 0.0.29                | AsmodeusCore-1.12.2-0.0.29.jar                  | None                                     |
	| LCHIJA | forgelin                 | 1.8.4                 | Forgelin-1.8.4.jar                              | None                                     |
	| LCHIJA | bcextrapipes             | 1                     | bc-extra-pipes-1.12.2-1.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bcoreprocessing          | 1                     | bc-ore-processing-7.99.24.4-1.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftbuilders       | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcompat         | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftenergy         | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftrobotics       | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | fermion                  | 1.0.2+hotfix.testless | Fermion-1.0.2+hotfix.testless.jar               | cc2bf3016f756771230cdc4fac0ec50efdf8d212 |
	| LCHIJA | bcrf                     | 1.5.4                 | buildcraft-rf-1.5.4.jar                         | None                                     |
	| LCHIJA | carryon                  | 1.12.3                | carryon-1.12.2-1.12.6.20.jar                    | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chiselsandbits           | 14.33                 | chiselsandbits-14.33.jar                        | None                                     |
	| LCHIJA | refinedstorage           | 1.6.16                | refinedstorage-1.6.16.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | expose                   | 1.1                   | expose-1.1.jar                                  | None                                     |
	| LCHIJA | exposer                  | 1.2                   | exposer-1.2.jar                                 | None                                     |
	| LCHIJA | galaxyspace              | 2.0.17                | GalaxySpace-1.12.2-2.0.17.jar                   | None                                     |
	| LCHIJA | opencomputers            | 1.7.5.192             | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCHIJA | galacticcomputers        | 1.0.0                 | GalacticComputers-1.0.0.jar                     | None                                     |
	| LCHIJA | ironchest                | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHIJA | irontanks                | 1.12.2-2.1.0-beta.18  | irontanks-1.12.2-2.1.0-beta.18.jar              | None                                     |
	| LCHIJA | mcjtylib_ng              | 3.5.4                 | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LCHIJA | stevekung's_lib          | 1.2.0                 | SteveKunG's-Lib-1.12.2-1.2.0.jar                | None                                     |
	| LCHIJA | moreplanets              | 2.2.2                 | More-Planets-1.12.2-2.2.2-GC280.jar             | None                                     |
	| LCHIJA | nevokacore               | 1.0.2                 | nevoka-core-1.0.2.jar                           | None                                     |
	| LCHIJA | xnet                     | 1.8.2                 | xnet-1.12-1.8.2.jar                             | None                                     |
	| LCHIJA | ocxnetdriver             | 1.0.3                 | ocxnetdriver-1.0.3-b17.jar                      | None                                     |
	| LCHIJA | opendisks                | 0.1.0.3               | OpenDisks-MC1.12.2-0.1.0.3.jar                  | None                                     |
	| LCHIJA | reborncore               | 3.19.5                | RebornCore-1.12.2-3.19.5-universal.jar          | None                                     |
	| LCHIJA | rebornstorage            | 1.0.0                 | RebornStorage-1.12.2-3.3.4.1.jar                | None                                     |
	| LCHIJA | refinedrelocation        | 4.2.37                | RefinedRelocation_1.12.2-4.2.37.jar             | None                                     |
	| LCHIJA | refinedstorageaddons     | 0.4.5                 | refinedstorageaddons-0.4.5.jar                  | None                                     |
	| LCHIJA | refinedstoragerequestify | ${version}            | refinedstoragerequestify-1.12.2-1.0.2-3.jar     | None                                     |
	| LCHIJA | taiga                    | 1.12.2-1.3.3          | taiga-1.12.2-1.3.4.jar                          | None                                     |
	| LCHIJA | tcomplement              | 1.12.2-0.4.3          | TinkersComplement-1.12.2-0.4.3.jar              | None                                     |
	| LCHIJA | tinkersoc                | 0.6                   | tinkersoc-0.6.jar                               | None                                     |
	| LCHIJA | worldedit                | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
	| LCHIJA | morerefinedstorage       | 1.1.10                | morerefinedstorage-1.2.01.jar                   | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MixinBooter (.mixinbooter-4.1.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
OpenDisksUnpack (OpenDisks-MC1.12.2-0.1.0.3.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
  net.thesilkminer.mc.fermion.asm.common.FermionTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.79' Renderer: 'GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 0
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz]
## Description of the problem
>[Put Oxygen Tanks In the Oxygen Vent]

**Comment by Silfryi** [comment]
Old AR version.
