### ISSUE TITLE
FIX IMMEDIATELY

### ISSUE THREAD

**Issue by BraveCaperCat** [Advanced-Rocketry/AdvancedRocketry#2295]
> Old AR version.
YOU ARE THE WORST
Can NOT Update
(Using Forge App)

**Comment by Silfryi** [comment]
I locked the issue for a REASON. UPDATE, stop bringing it to us. There is a _major version change_ you have not done. Update to 2.0.0-257 and stop opening new issues. I would like to ask you how I you think it will get fixed if you don't update to the code containing the bugfix? This issue will be locked too. Go to the discord if you need more update help than below.

You need to be on the latest beta. You need to change your release preferences in the settings to "beta" and then you should be able to see them. This is dumb of the CF app but it's how it is.
