### ISSUE TITLE
STOP

### ISSUE THREAD

**Issue by BraveCaperCat** [Advanced-Rocketry/AdvancedRocketry#2300]
Fuck off with the spamming. I was _asleep_ for fucks sake. Anyway, about antique atlas. I saw MANY mixin errors and assumed one about AA was the error - since you **did not provide a modlist** (which is on you, not on me) for me to check against, I assumed it was AA. Since AA isn't in the pack then I think the _root_ cause is supplementaries. Either way there is NOTHING of our code in that stacktrace. We have no part here.

_Originally posted by @Silfryi in https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2299#issuecomment-1061112183_

Modlist=Modpack

**Comment by Silfryi** [comment]
You're being such a pill and so unhelpful I am banning you from the repo. Goodbye. Linkng to https://github.com/simibubi/Above-and-Beyond/issues/396 just to make sure they see it.
