### ISSUE TITLE
[sugesstion] adding tier thrusters and etc.

### ISSUE THREAD

**Issue by slendercreeper1010** [Advanced-Rocketry/AdvancedRocketry#234]
I think it would be intersting to add tier involved rusters and LFO tanks, witch, we will probably made fron non-earth planets and moons, because sometimes its impossible to launch a beautiful (gigantic) rocket without having problem with thrust or tanks witch causes the beauty to go away, and ugly to show up ;)

**Comment by zmaster587** [comment]
I had been planning teirs for a while, and have been searching for a way to keep people from never using the lower teir ones, this requiring exotic materials would work beautifully though.

**Comment by slendercreeper1010** [comment]
WOW! I have never thought someone would use exotic matter for such perpouse! I would look forward to see it

**Comment by slendercreeper1010** [comment]
I have read matter instead of material. I'm just into SCI-FI, so i thought that exotic matter engene is good enought to lift the rocket 👍 ;)

**Comment by zmaster587** [comment]
that could work too, could make exotic matter something akin to UU as well as being used to top tier components

**Comment by slendercreeper1010** [comment]
That would be nice ;)

**Comment by zmaster587** [comment]
Added an advanced thruster for 1.0.0

**Comment by wormzjl** [comment]
Might consider a tiered thruster / fuel combination
Like hydrazine, LH2/LOX, methane/LOX, etc.

**Comment by CTH999** [comment]
And, if non-warp interstellar travel, maybe Ion Engines, takes a long time to speed up, but once it does, it's almost at the speed of light!

**Comment by slendercreeper1010** [comment]
As far as I know the ion engine doesn't work like that. It just let you travel with minimal fuel cost. But solar sails can do the job

**Comment by CTH999** [comment]
Not quite. It's sending it out at a huge percentage of the speed of light, but, it's like blow air out of you mouth. You will get to almost the speed of light, but, it will take hundreds of years. You are right about the low fuel cost. A container of hydrogen on a normal rocket= no propulsion, need o2

On an ion drive 1 canister of h2= thousands of years. (I like space)

**Comment by slendercreeper1010** [comment]
Me too ;). Actually I was thinking about another way of FTL traveling: a wormhole. You will need to have a warnhole opening system on board (it should be HUGE and expensive to build) and a LOT of energy, but it could get you to another galaxy with a blink of an eye

**Comment by CTH999** [comment]
Yup, I actually want to figure out how to make a wormhole IRL, I just need to figure out artificial gravity...

The wormhole should be a multiblock that requires a gravity generator in it, and I just remembered an idea I had for AR, for even more than one universe.

Putting it on now.

**Comment by slendercreeper1010** [comment]
I suppose you meant wormhole IRL in the second paragraph. Building a wormhole itself is weird

**Comment by CTH999** [comment]
Yes, a wormhole is weird (That's one of the definitions of Quantum Physics), and would require lots of gravity.

However, the multiblock should include a gravity-gen.

And, since it's instant, there should be risk. IE if it loses power as part of the ship is in it, any star systems you pass by would be anihlated as Particles that where barely moving are suddenly thrust into a different location of space, where, relative to them, they where moving faster than light. That would mean severe consequences for you, yours station, and the universe...

Who knows.

**Comment by slendercreeper1010** [comment]
I just imagined for a second combining AR with a GregTech v5.09. Personally, if part of my ship had been  annihilated that way I would ragequit. 
But non the less, it would be better generator to have a wormhole station as the independent station, or a gate (I remembered a Stargate series). It will allow you to connect two parts of the space-time continuum. (maybe something similar to how wormholes in stellaris stellaris

**Comment by slendercreeper1010** [comment]
But non the less, it would be better to have a wormhole station as the independent station, or a gate (I remembered a Stargate series). It will allow you to connect two parts of the space-time continuum. (maybe something similar to how wormholes in stellaris Work)

**Comment by CTH999** [comment]
Yup, and other universes,
The destroyed part would be if you have way to little power, or press the collapse button. That could be an add-on some make though. (I never played GregTech v5.09.) I see what you mean, or, maybe it could be a config option (Off by default) when they add in [Hard Mode](https://github.com/zmaster587/AdvancedRocketry/milestone/3).

Also, If distance becomes a factor in warp-travel, this would be instand, but require power (Lots) And dilitium. While going to a nearby star system like that makes no sense, going to another galaxy with a wormhole makes a lot of sense. Then, it's the only way to get certain [Certain Types of Exotic Materials](https://github.com/zmaster587/AdvancedRocketry/issues/945), which could make it safer. These are all just ideas though. (I haven't ever rage quite, but, I do creative... and save a lot...)

**Comment by slendercreeper1010** [comment]
I played with GregTech and I know how hard it is to create all the components for the machinery like warp drive (for GregTech it's near middle-endgame) so I would definitely ragequit.

I think it would be interesting to find exotic types of stars (like neuron and quark stars, red and black dwarths, and black holes of course) and harvest those components from them

(maybe a Russel teapot, please)

**Comment by CTH999** [comment]
Yup, I heard rumors about gregtech, hence I never tried it in survival :)
So, I see what you mean. Defiantly shouldn't be that hard, but it shouldn't be easy. (Come on, you bending space and time to the point of touching.) If we want, one of the exotic matter (That's craftable via a special multiblock is [Negative Mass](http://www.rochester.edu/newscenter/vamivakas-microcavity-negative-mass-generate-lasers-290202/) And  [More Negative Mass](https://phys.org/news/2017-04-physicists-negative-mass.html). It's used to prevent the wormhole from collapsing in on itself, but, let's just assume they have the tech to keep it "stable", it's semi-hard to get, gets used up along with power (Proportional to the distance and the size of the station (I'll try to make an equation)), and is hard to mass produce without more exotic matter, (Gotten from neutron stars, pulsars, the like) and [Other Universes](https://github.com/zmaster587/AdvancedRocketry/issues/1099) for more [Exotic Matter](https://github.com/zmaster587/AdvancedRocketry/issues/945). At first it's semi-hard and semi-expensive, and defaults to semi-safe, and eventually, you can combine them with [Warp Coils](https://github.com/zmaster587/AdvancedRocketry/issues/935) and more exotic matter, to make it safer, faster, more efficient, have negative mass have a longer half life, and make it trivial-ish. And, without the configured hard mode option, it doesn't matter if it's a system that would destroy you, and with it enabled, it's more realistic, and more rage inducing!

There would be a negative mass containment unit (NMCU) That uses power to keep it stable longer, it will only be able to be in the container for transferring for under 2-min, and there would be a special cable to be able to transfer it as well.

P.S. The reason why it needs to be different than IRL, is that the more you have in the universe, the less stable it is, and of course, with just one atom, it decays almost instantly.

**Comment by slendercreeper1010** [comment]
There is only one problem: if it will be hard to create, calculate and prepare everything people won't use it. We all know that most of the people playing Minecraft - 6-15 years old. We both can handle all that you've listed, but not everyone. So maybe something a little bit simpler?

**Comment by CTH999** [comment]
Yeah, maybe... 
Removing the negative mass part maybe, or making it configurable.

Or, it could just be portrayed as a fuel source, with a link for what It is in the download.
Meaning, people who don't understand it, think it's like the dilithium for the warp core, while people who read it, know why it's there. People who don't read it think the "Stabilizer" Is a fancy tank, while people who understand know why it's there, and we can make it not decay, but it has to go straight from the tank to the wormhole generator.

Or, just another fuel.

Though I think having it look like just fuel and be simpler will be better. It will just have multiple recipes.

Though, what do you think would work?

**Comment by slendercreeper1010** [comment]
It would be better to have a special input for it. And it would be generated via a special machine around the pulsar, for example

**Comment by CTH999** [comment]
That's even better, because they aren't 100% sure about -mass, and for simplicity, it's energy holding it open, and this material helping. And, maybe you could extract some of the core of the neutron star, and boom, you have a block that's unable to be broken by any explosion, and takes a while to mine. Not to mention one block weighs 1000000+tons, so, it's pretty strong. Also, it would be cooler to have more than just gas mining and asteroid mining missions, (I.E. Magnatar Mining!)

**Comment by voidsong-dragonfly** [comment]
Second tiers of engines have been in for quite a while. The advanced engines have 5x the thrust for 3x the fuel cost.
