### ISSUE TITLE
Grayscale textures

### ISSUE THREAD

**Issue by MechWarrior99** [Advanced-Rocketry/AdvancedRocketry#311]
So, I was going to change the copper stuff in AR to match the rest of the copper in my pack. But then realized that all the textures are grayscale... Any chance of using normal, none grayscale textures?

**Comment by zmaster587** [comment]
The reason for the greyscale textures is that it increases efficiency and greatly reduces the amount of textures and and amount of fiddling that needs to be done with 1.10's systems.  I would prefer to avoid making a texture for each material if possible.  

However what I can fairly easily do is to add a config to change the color multiplier for each material

**Comment by MechWarrior99** [comment]
yeah, I can understadn that
That would be nice. Would be a bit fiddly, and not great for resourcepacks. But for modpacks that would work just fine. Thanks :)

**Comment by voidsong-dragonfly** [comment]
As of 1.16.5, textures are now all their own files.
