### ISSUE TITLE
[Suggestion] More Suit addons

### ISSUE THREAD

**Issue by EvilCooky** [Advanced-Rocketry/AdvancedRocketry#356]
A bunch of suit addons.

First, Armor Plates to be installed in every Suit part, to give your space suit some armor

Jump boost upgrades in for the boots, to allow two block high jumps.

Step assist upgrades for the pants

It would also be nice to add crafting reipies to make other armors space proof. it could be installed as an upgrade for the EnderIO Darksteel Armor.

**Comment by GazbonicAcid** [comment]
there's already a suite addon that gives jump boost.
It's the bionic leg for the pants that gives jump boost.

**Comment by voidsong-dragonfly** [comment]
Space suit purposely does not have armor value, there's the enchantment if you need that. As said, the other two have been covered.
