### ISSUE TITLE
[Suggestion] Auto Insert Asteroid Chips into Rockets.

### ISSUE THREAD

**Issue by EvilCooky** [Advanced-Rocketry/AdvancedRocketry#445]
I recently wanted to do my whole resource mining with Ateroid Mining Missions, just for fun.

But there is no way I know of, to have the Asteroid ID Chip inserted into the Rockets Guidance Computer other then doing it by hand.

Is there a way to do this automaticly?
If not, How about you add a slot in the Monitoring Station that places any ID chips that come in, into the linked Rockets Guidance computer.

**Comment by voidsong-dragonfly** [comment]
Guidance Computer Access Hatch.
