### ISSUE TITLE
[suggestion] Port addition to multiblock machines

### ISSUE THREAD

**Issue by wormzjl** [Advanced-Rocketry/AdvancedRocketry#446]
Well if possible, trying to design some process but was blocked by the port issues
1. add fluid input/output port to crystallizer
2. add fluid input/output port to precision assembler
3. add item input/output port to electrolyzer

**Comment by zmaster587** [comment]
Will see if I can work them in

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
