### ISSUE TITLE
Allow specification of WorldType when making custom planets

### ISSUE THREAD

**Issue by Divineaspect** [Advanced-Rocketry/AdvancedRocketry#449]
I love me some worldgen options, Biome's o Plenty, Quark's Realistic, ATG, etc. Could we get the ability to assign these to planets to go along with the biomes for them?

**Comment by zmaster587** [comment]
I'm not sure how doable that would be because I have to provide my own worldgen code to be able to specify biomes.  I might be able to do something about heightmappish stuff though.  Will look into when I get an opportunity

**Comment by voidsong-dragonfly** [comment]
At this point I believe this to be done better through Vanilla dimension datapacks and dimmapping - they can provide generator options we, requisitely, could not, such as (I believe) Terraforged generation options.
