### ISSUE TITLE
Suggestion: Gregtech compatibility

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Advanced-Rocketry/AdvancedRocketry#483]
I opened an issue on the GT5U Experimental github asking them to make the new Low Grav Processing work with Advanced Rocketry. There are two other potentially useful points of compatibility that I can think of at the moment. Current GT5U configs specify whether an ore can generate on the Moon, Mars, or asteroids in the file WorldGeneration.cfg. It would be useful if Advanced Rocketry could read these config options and use them to return naquadah ore from automatic asteroid mining missions, for example. Also, it would be neat to be able to land on Titan and have Titan generate with limitless Gregtech reserves of light/medium/heavy oil and natural gas, oceans of Buildcraft/Magneticraft/Gregtech oil of all kinds with infinite water mechanics, and GT oilsands ore.

**Comment by wormzjl** [comment]
I'd suggest use COG

**Comment by zmaster587** [comment]
I could look into adding the ability to specify what liquid the ocean is made of for each planet.  As for the ores, I cannot say if i can get around to it or not, it should be doable with the current settings for AR, bit tedious though.  Unfortunately i currently have a lot on my plate right now so I need to focus more on the things that currently cannot be done or are broken, but I'll consider adding that as a feature when time frees up

**Comment by bHXDgiuMa5yLHyC8** [comment]
It seems that if Advanced Rocketry generated a dimension with "Titan" or similar as its Class Name then it would be simple enough for me or other users to add infinite Gregtech drilling rig "underground fluid" deposits just by tweaking Gregtech's configs. One could even add deep underground deposits of molten cheese to the Moon. 🧀

**Comment by zmaster587** [comment]
Generating new classes at runtime is a very difficult and is a rather hacky way to solve a problem.  (It's almost as bad as trying to have your mod generate the code for the mod at runtime from a template).  Does gregtech have no way of specifying a dimension ID to use as a modifier for terrain generation?

**Comment by bHXDgiuMa5yLHyC8** [comment]
Dimension ID works fine too.
