### ISSUE TITLE
Feature Request or as a side mod!

### ISSUE THREAD

**Issue by Tyrantin** [Advanced-Rocketry/AdvancedRocketry#504]
Interaction between AR an AE2.

Was thinking about it but have no Exp Modding. 
Monitors for:
Rocket monitoring station
Gravitational controller
Orientation
Warp Controller

Also:
Fluid Storage modals (Not the Tanks):
               Multi-block Structure ( Think of it as for Oxygen Storage for Space Stations )
                      -- Could be designed as a Cylinder like the Fuel only larger scale 3X6, 4X8, 5X10 and 6X12
                      --Or however you want to do the Sizes.

**Comment by voidsong-dragonfly** [comment]
AE2 adds monitors for things it handles, not for things it doesn't - and AE2 handles none of those four things. As for large liquid tanks, AR isn't particularly meant for liquid storage, get another mod for that - we only have tanks because they're an absolute necessity for gas mining.
