### ISSUE TITLE
Limit blocks for rockets

### ISSUE THREAD

**Issue by gdarai** [Advanced-Rocketry/AdvancedRocketry#526]
Hi,

I have also another question... can I somehow limit, which blocs can be used for building rockets? So the player is not building rocket from coblestone?

BTW, mapping of planets to existing dimensions seems to work. Good job.

Thanks, Darai.

**Comment by zmaster587** [comment]
Currently no, I thought I implemented this way back when facades on rockets were broken, will add a config today.

**Comment by gdarai** [comment]
There is some sealable block whitelist.... that is just for sealability? Like "what blcks the hull of the space station has to be made of to be sealable?"

Default is empty. Does it mean that by default the ship cannot be sealed?

**Comment by zmaster587** [comment]
That's just for atmosphere calculations for space stations and such, the mod calculates what blocks are sealable by checking if it's a full block or not, but there may be some blocks that should be sealed that the original algorithm doesn't catch, which is why that config is there.

**Comment by voidsong-dragonfly** [comment]
We have a rocket block blacklist for now, funnily enough.... just not for the reasons you were thinking of, it was to remove flowing water and fire and stuff as parts of rockets. You can use that.
