### ISSUE TITLE
AGiLE-EaGLE1994's ultimate ideas thread

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#586]
I will be posting all of my ideas for AR here from now on.
So far, I've come up with:
Planets:
Venus type planets and biome
Saturn-like gas giants with the correct color
Jupiter-like gas giants with the correct color
Large (Saturn), medium, (Uranus) and small (Jupiter) rings for planets
VTHL (Vertical takeoff, horizontal landing) rocket engine for horizontal shuttle bays in Star Trek style warp ships
Antimatter, fusion and dilithium engines for rockets
Different star types and sizes
Multi-star systems
Space bed which has an airtight compartment and allows sleeping on airless dimensions
Alien versions of overworld mobs for the alien forest and other alien biomes
Alien ghasts for gas giants and Stormlands biomes?

**Comment by AGiLE-EaGLE1994** [comment]
Also perhaps making individual XML files for different worlds? Either by naming the XML file after the world in the Advanced Rocketry config folder or making a PlanetDefs folder for each world in the world save folder?

**Comment by AGiLE-EaGLE1994** [comment]
Perhaps you could make a monitor for the Warp Core and a Holodeck?
They'd both have an LCARS style interface and the holodeck would be customizable like the AR planets are.
When you go into the holodeck room and choose a simulation from the interface, you get teleported to another dimension which represents said simulation, and when you die, you reappear in the holodeck room you accessed the simulation from.

**Comment by zmaster587** [comment]
The warp controller as it is functions as a remote monitor for that warp
core, it's just not currently named as such.  So any additional features
for warp core monitoring will likely end up there.

As for the holo deck.  While it is a cool concept commonly seen in star
trek, the scope of the idea is so large it really could be it's own mod.

**Comment by AGiLE-EaGLE1994** [comment]
Another idea: Possibility to make stars with 140 mass and higher go Supernova with a special machine? Maybe the a superlaser that can be used to destroy planets, moons, etc? With the exception of space stations and Earth, and a configurable setting or boolean option for planets and moons which makes them immune to the superlaser? Like "LaserImmune = true/false" or something like that?
And possibly a ship with the ability to CREATE planets, moons, and stars using dilithium as fuel?
Pregenerated space stations with the ability to import schematics?
randomly generated abandoned warp ships which can also be defined via schematics?

**Comment by AGiLE-EaGLE1994** [comment]
How do you use the entity bypass list? What format should the entity names be in? I can't get it to work.
I want to add Custom NPCs and players to the bypass list but it won't work.
I did it like this: 
    # list entities which should not be affected by atmosphere properties [default: ]
    S:entityAtmBypass <
        EntityPlayer
	EntityCustomNpc
     >
Did I do it right?

**Comment by smmarkvard** [comment]
Can anyone explain how with format the entity should be in?

**Comment by AGiLE-EaGLE1994** [comment]
I have more ideas! Could you make it possible to specify asteroid belts with a dim mapping ability in star systems, that way I don't have to specify the Galacticraft Asteroids dimension as a planet instead of an asteroid belt?
Another idea: Custom planets that are MC Style with lunar phases (In a similar look to the vanilly MC moon and sun on the overworld instead of the hyper realistic ones 
Solid Planet types: 

Mars-like (Looks almost exactly like Mars)
Earth-like (Looks almost exactly like Earth)
Postgaian (Looks like Earth, but with boiling oceans and lower sea level)
Moonlike (Looks like the Moon)
Lava planet 
Venuslike (Looks identical yo Galacticraft Venus, used for Hot Dry Rock planets)
Ocean planet (For planets with ocean biomes only)
Jungle planet (Lush green planet, used for jungle, plains and forest biome planets)
Desert planet (Used for mesa and desert biome planets. Covered in sand with small lakes.)
Orxonian (Highly polluted planet with oceans of toxic sludge, toxic atmosphere and mutated life as well as large cities)
I'll make planet icons with phases for you so you don't have to make them.

**Comment by AGiLE-EaGLE1994** [comment]
Marslike and Orxonian planets:
![marslike_phases](https://user-images.githubusercontent.com/11968498/62248781-f063c180-b3b6-11e9-812f-2b3345f431d0.png)
![orxonian](https://user-images.githubusercontent.com/11968498/62248782-f0fc5800-b3b6-11e9-8e6f-52a844223a86.png)

](url)

**Comment by voidsong-dragonfly** [comment]
All of these are at this point covered by other issues. Closing this one as it's enormous and annoying to tackle as a whole
