### ISSUE TITLE
Lack of mod documentation

### ISSUE THREAD

**Issue by Finalruner** [Advanced-Rocketry/AdvancedRocketry#640]
Mod is overall confusing for beginners, please update the wiki or add an in game tutorial for the mod

**Comment by zmaster587** [comment]
I'm working on it...  I did go through a make a massive update to the listing of blocks the other day

**Comment by zmaster587** [comment]
If there's anything in particular you want to see in the docs let me know

**Comment by duncanwebb** [comment]
The Biome Scanner would help, it looks like it should fly. (version 1.1.7)

**Comment by zmaster587** [comment]
done 
http://65.78.115.159:8000/AdvancedRocketry/blocks/BiomeScanner.php

**Comment by duncanwebb** [comment]
Excellent, helps, thanks.
The Gravity controller multi-block would also be helpful; I guest that this sits either on another planet or the space ship.

**Comment by duncanwebb** [comment]
The Electric Arc furnace is not documented in Blocks page.

**Comment by duncanwebb** [comment]
The getting to space page links to the electric arc furnace page but returns a 404 error. I've found a couple of broken links mostly due to uppercase lowercase mismatch.

**Comment by duncanwebb** [comment]
The Planet Selector is another block that could do with a page.

**Comment by zmaster587** [comment]
alright, I'll make the Electic arc furnace a priority.  Can you list what pages contain broken links if you get a chance?
Planet selector added to my todo list.

On that note, I also am planning on adding a guide on launching space stations, a guide for asteroid mining missions, and a guide for gas mining missions.

**Comment by duncanwebb** [comment]
No problem, will do. Here's one on http://arwiki.dmodoomsirius.me/items/modularSpaceSuit.php the Gas Charge Pad links to the space suite page. Whenever I find one I'll post it here.

**Comment by duncanwebb** [comment]
I've figured out most of the mod, my space station is https://youtu.be/0KYdiB3-W2Y and asteroid missions https://youtu.be/tpmLXClDfng. I've not yet figured out gas mining or how to automatically fuel, load and unload rockets. I've not figured out gas mining (type of tanks) and putting the linker in a docking pad to link two destinations.

**Comment by duncanwebb** [comment]
Looks like docking pad is missing, there is a broken link from the linker page. The linker page says that shift-right click clears the linker - it doesn't seem to (version is 1.1.7). Not sure if this is a documentation bug or another issue.

**Comment by zmaster587** [comment]
sounds like that's another issue, you may have to be moused over a block for the clear to work.  Also noted, I'll fix the link on the linker page.

**Comment by duncanwebb** [comment]
Yes that works, highlight a block, like dirt, and shift right click clears the coordinates. Many thanks

**Comment by zmaster587** [comment]
yep, no problem.  Will see if it can be changed so you don't havce to hilight something

**Comment by duncanwebb** [comment]
The Crystallizer could do with a page. In the Getting to Space Guide in the section Building basic Infrastructure there are machines that could be linked to a blocks page.

**Comment by Tronzoid** [comment]
How do I use observatory? it does not seem to be working even after removing and replacing blocks on structure, when I use it, the data page is blank apart from range details and power

**Comment by duncanwebb** [comment]
You need to take a data chip and put it into the data port and feed the distance data, mass, or composition into the buffer and then break and reform the structure then you should see the asteroid tab. You can add data to all three and have three data ports. You will have needed to send up some satellites and put the chips into the satellite station.

**Comment by Spaig** [comment]
Also, some general information would help a lot too - such as wiki pages on the various multiblocks and a more comprehensive beginner's guide. Just mentioning that the multiblocks have more than one layer in the"Getting to Space" guide would have saved my players a lot of time and frustration :)

**Comment by Hillage** [comment]
I'm currently trying to figure out how to get to various planets. The lack of documentation is VERY rough and I'd bet that many people turn away from packs when they reach this mod. When I figure out how everything pieces together in the latest versions I'll try to post videos to help

**Comment by duncanwebb** [comment]
There is a good video about getting to other planets from the author zmasterfox and Wisper Fire in her Forever Stranded series and I have a few of my own as Duncan Webb

**Comment by wisathestray** [comment]
A player- updatable Wiki would be great and take some pressure off the dev.  Tutorials by YouTubers are the closest thing to user documentation that I've been able to find, so if a Wiki already exists, then it needs to be way easier to find.

**Comment by dmodoomsirius** [comment]
He does have https://github.com/zmaster587/AdvancedRocketryDoc which is the repo where the wiki is.

**Comment by sdfg2** [comment]
Are you supposed to be able to launch satellites from a space station?  I can't tell if it's a bug that I can't, or if it's not allowed, the wiki is a bit unclear on the matter.

**Comment by voidsong-dragonfly** [comment]
Closing due to old issue and recent wiki updates.
