### ISSUE TITLE
{enhanchements} drill laser beam

### ISSUE THREAD

**Issue by tobiasvdp** [Advanced-Rocketry/AdvancedRocketry#734]
It would be nice to have a beam emitting from the drill when it is active. Would make a great effect.
You got the beam part already down more or less with the elevator I would think.

**Comment by zmaster587** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/3536685/27255760-61e61ca0-5373-11e7-890a-e9f489a91f54.png)
(image is back from when AR was a GC addon, oddly enough the space laser was the first thing made for the mod)

**Comment by tobiasvdp** [comment]
Looks good, may even be a bit more intense beam for my taste
