### ISSUE TITLE
(Enhancement) Add decorative iron-like block

### ISSUE THREAD

**Issue by rkane31174** [Advanced-Rocketry/AdvancedRocketry#754]
Iron blocks are perfect for space stations, but they're too expensive to be feasible in survival mode.
Can we have a decorative block that looks like iron but is cheaper? That way we don't need to make stations out of stone bricks, or worse: cobble.
Galacticraft has something similar: the tin decoration block. By crafting a tin plate with a stone block, the player receives a tin decoration block. It doesn't look quite as good as iron, but it's 'spacey' nonetheless.

Maybe Iron/Tin/Aluminum plate + stone block = station block?

**Comment by dcbartlett** [comment]
libVulpes (dependancy for this) has tons of blocks for this.  They are made from metals (copper, gold, tin, aluminum, titanium, etc).  Also there is concrete (you make this for the launch pad) and it looks like a SMP safe block (doesn't cause lag).  These could be some options.

**Comment by rkane31174** [comment]
The problem with these blocks is that they are just as expensive, with each one costing nine ingots of their respective metal. That's a high price to pay for having a nice looking station.

**Comment by dcbartlett** [comment]
I would look into the Chisel mod.  This mod has relative inexpensive blocks for visual purposes as well as the ability to make other blocks look different (chisel tool).

I'll look into seeing if i can add a "Space Station" block to it and submit a PR.  No promises though.

**Comment by voidsong-dragonfly** [comment]
This is provided in the form of machine structure, which is not a TE and looks metallic.
