### ISSUE TITLE
[Enhancement] My MasterList Of Ideas For Advanced-Rocketry

### ISSUE THREAD

**Issue by Johbii** [Advanced-Rocketry/AdvancedRocketry#812]
### Planet Selector Improvements<h3>
- Configurable music in planet selector
Ever since I played mass effect and then saw the planet selector in this mod i've been wondering if you could add this feature. *"Uncharted Worlds"* from mass effect is one of my all time favorite songs and we **NEED** to be able to configure music for the planet selector

- Fade in and out on planet  selector
Along with playing music on the planet selector, having a simple fade in or out would really make using it a very cool experience. I need to be able to make the normandy in minecraft, zmaster, I need to.

- Making the planet selector project a holograph of star system
[Matter Overdrive](https://minecraft.curseforge.com/projects/matter-overdrive) had a [Star Map](https://mo.simeonradivoev.com/wp-content/uploads/2015/06/Star-Map-Galaxy-Screenshot.png) that aesthetically was much of what I dreamed of when I first heard "Space Mod For Minecraft" but when the mod author quit modding, he didn't finish the galaxy system feature he was planning. If you could make the planet selector look like his block, it would be a major improvement.

### Shuttle Concept<h3>
- Shuttles
Possibly out of the scope you wan't for the mod, but having a shuttle system where blocks like a steering wheel "with a fancier space name" are present the shuttle can travel but like the rocket, it is limited.

- Reasoning
To me, the mod is a mixture of star trek and traditional realistic space travel. But for me, I am much more interested in the aesthetics and style of **far** future space fiction like star trek. **Imo**, it is kind of silly having such advanced warp core technology, powering it with crystals, and a faster than light aesthetic, yet we still use traditional rockets? My idea was that the rockets would be used as early game to actually establish star ships and stations, however the shuttles can be used once you have the star ship infrastructure set up. 

- Why it's better than rockets
I **very** much like the rockets in the mod, building them is extremely fun, but along with the far future aesthetic that it misses, it is also a fairly hard rendering issue. It must be very ahrd to port from version to version with a giant rendering event with particle effects and so on. I would be just as if not more happy with this mod of there we're shuttle system, it doesn't cause lag, it avoids possible crashes, it's easier to port versions, and it has a better aesthetic **IMO** than rockets. You don't need to use particle effects or play an animation or anything with a shuttle system.
### Unified Galaxy Changes<h3>
- Making A Mliky Way
Another idea borrowed from mass effect, having the star systems contained within an overall milky way galaxy would be extremely entertaining. Having a unified galaxy would mean that the star systems would have a background and place among the galaxy. The milky way is huge and it could fit so many star systems that fitting them all within would not be hard at all, and it gives some textures and particles that could be used for the planet selectors new hologram.  :p

**Comment by Jummit** [comment]
You can actually build shuttles (which are not very useful) with Archimedes ships. Fly around your space station and attach it to a docking port is very fun. But shuttles which can go to the planet like in star trek would be the best thing ever.

**Comment by voidsong-dragonfly** [comment]
Closed due to the majority of this being either implemented (holoselector) not happening any time soon (music loading is a PAIN) or moved to a central issue (ships, #2036)
