### ISSUE TITLE
Suggestion: make space suit use separate armor slots from the main armor

### ISSUE THREAD

**Issue by Trinsdar** [Advanced-Rocketry/AdvancedRocketry#836]
Like said in the title, could you make the space suit part of separate armor slots from the main armor so someone can still wear regular armor?

**Comment by Arsomang** [comment]
Yes please. OR add armor plating modifications you can make for the suit. So we can have more armor for fighting bosses on the different planets.

**Comment by EvilCooky** [comment]
Other suggestions would be to add support for other armors.
For example, add a space suit upgrade for EnderIO Darksteel armor.

**Comment by Archilyte** [comment]
isnt there an enchantment that makes armors sealed
and a crafting recipe of all armors to have a tank via the chemical thingy?

**Comment by zmaster587** [comment]
@Archilyte There should be, yeah.  Can't remember if it was added before or after 2017 though.

**Comment by Silfryi** [comment]
Tank+diamond for chest, diamond for everything else. I believe it's in the chemical reactor.
