### ISSUE TITLE
[enhancement] Lasers and shields!

### ISSUE THREAD

**Issue by Jummit** [Advanced-Rocketry/AdvancedRocketry#846]
Make a block that shoots a laser **and breaks the blocks that are in line with it**! Here are some little and fast sketches:
Laser turns to the opponent side of the redstone signal
![alt text](http://i.imgur.com/KhVSnHJ.png "Laser turns")
Laser gives output on the opposite side of the laser if a block is destroyed.
![alt text](http://i.imgur.com/F5PayPz.png "Laser gives redstone output")
Laser breaks blocks
![alt text](http://i.imgur.com/ZZoAFPE.png "Laser breaks blocks")

#### You can color you're laser with dye!

Now, to protect you're ship from being shot, you can install shields that use power when the ship is attacked. When the shield is down, the laser will be able to damage the ship again.

**Comment by EvilCooky** [comment]
And what purpose should that "Laser" have?

I find it funny that people just shout out "Hey, make a laser" and expect something to happen.

**Comment by Jummit** [comment]
> And what purpose should that "Laser" have?
Oh, sorry about that. It should break blocks. Thats it.

**Comment by EvilCooky** [comment]
ok, after you added soem purpose to your idea, I can see what you wanna acomplish.
But your ideas is based on the assumption that there are free controllable space ships in this mod, which is not the case.
You only have Rockets that fly to the top of the world and then change Dimensions.

While Space combat would be cool, I don't see how it could be realised with the current state of the mod.
The best solution would be adding another mode that adds spaceships as rideable entities, along the lines of Planes from Flans mods.

**Comment by Jummit** [comment]
I used archimedes ships for my flyable space ships, and it worked well. But you cant put lasers on them, though...

**Comment by CTH999** [comment]
Also, this could work interestingly with [Suggestion- Weapons+ Tools+ Combat](https://github.com/zmaster587/AdvancedRocketry/issues/1156) and also [Sugestion CC And OC Compat](https://github.com/zmaster587/AdvancedRocketry/issues/147) (Since you could control them)
This is just a suggestion!

@Jumit I completely agree with this suggestion BTW!

**Comment by voidsong-dragonfly** [comment]
AR is a peaceful mod and will not include weapons.

**Comment by MrEyeballs29** [comment]
It is true this mod is about exploration not combat. Since having combat is super hard to implement.
