### ISSUE TITLE
[enhancement] Boarding

### ISSUE THREAD

**Issue by Jummit** [Advanced-Rocketry/AdvancedRocketry#849]
Make a block that scans the orbit for spaceships for a little bit of energy. Now these spaceships are available to be boarded or 'visited'. Youre spaceship gets cloned next to the target. The distance is the width of the bigger ship. The controls of these ships, like rotation and all these stuff is now the same. If one of the spaceships warps, it gets cut of off the other ship.

**Comment by ChetwyndKid** [comment]
Oooo I kinda like this idea. 
Not that it means anything that I like it...
Would be pretty good for modpacks, Although I guess I could custom build some ships and make them in a dimension and use the DimMapping in order to get to them... 
But I +1 this idea

**Comment by voidsong-dragonfly** [comment]
This does not work well with how MC handles TEs, especially with stations post-being-built having the possibility of network TEs or other problems when trying to move them. While technically possible, it's an utterly horrible idea for game stability as we can't ensure non-corruption of the world when doing it.
