### ISSUE TITLE
How do you locate rockets after they have landed, but not on launch pad?

### ISSUE THREAD

**Issue by Scuba-John** [Advanced-Rocketry/AdvancedRocketry#852]
My rockets aren't returning to the launch pad and I think this is a good feature. The pad doesn't have a docking pad that tell it to come back here, but there should be a way to locate it once it returns to the planet.. 1st rocket I was unable to locate, 2nd rockets landed 50-100 block away and when i resent I'm not able to locate it.

**Comment by Janrupf** [comment]
Well, they should return to the launchapd. But can you send a screenshot? Im not really understanding you. 

Unmanned Rockets?
Spacestation or planet?

**Comment by soronthar** [comment]
If the a unguided rocket reaches space, they do not return. If the rocket do not reach outer space and run out of fuel, they will return either on the pad or some blocks outside of it depending on the altitude they gained.
Note: This is purely empyrical information, from a lot of tests. I do not know what the code is supposed to do.

**Comment by Scuba-John** [comment]
Screenshots not available I left the game running while at work, it crashed and now stalls at 0% when I load the world.
Rockets were unmanned 
My first rocket setup was 4  liquid engines,8 fuel cells, 1` sate bay, 1 guidance. It went to space because the sate linked, but didn't  return to the pad. Monitor showed that it had returned to the ground and still had fuel remaining, but I couldn't locate it.  
My second rocket setup 5 liquid engines ,10 fuel cells, 1 sate bays, 1 guidance . It went to space left the sates and returned but not to the pad.
Since it wasnt on the pad i took it apart and rebuilt it adding 4  more sate bays. It went to space, left the sates and return, but i couldnt locate. Again monitor showed it had landed and had fuel remaining.

**Comment by zmaster587** [comment]
If a rocket is set to launch a satellite and unmanned it will land some distance away from the launch pad, though sometimes in unloaded chunks, so it may appear to get stuck in the tracking station sometimes.  

As for tracking where they land it could be printed in the tracking station or visible in world via a smoke flume.

**Comment by Frinn38** [comment]
Why didn't make a compass like item that can find the rocket when they land =)

**Comment by AujreliaLyon** [comment]
My unmanned rocket placed a satellite into orbit successfully, then "landed" about 200 blocks directly above the launch pad. screen shot attached.
![rocket returns to wrong y value](https://user-images.githubusercontent.com/43999013/46757279-b1357a00-cc97-11e8-97a7-19aaf0e8a8bf.jpg)

**Comment by voidsong-dragonfly** [comment]
This report is duplicated by #1754, and is otherwise intended.
