### ISSUE TITLE
Rocket Performance Configuration [analysis and suggestion]

### ISSUE THREAD

**Issue by gdarai** [Advanced-Rocketry/AdvancedRocketry#886]
So we have two parameters to configure how well will a rocket perform, how much stuff we need to put on for it to work. (Rocket, not WarpShip)
**fuelCapacityMultiplier
thrustMultiplier**

Summary of the tests below:
- There is a bug showing strange scharacteristics when there is not enough fuel.
- It is possible to build a flawed rocket which will pass the Scan but will have Acceleration 0 and will not leave the ground.
- The gravityInfluencesFuel switch does not change the rocket's performance or how big the rocket must be or how much fuel it must carry.
- The rocket consumes roughly the same amount of fuel no matter the setting.
- Both parameters can be floats and even < 1.
- thrust multiplier makes each engine to produce 10*mul[N] of thrust, lifting app. 10*mul blocks of what ever.
- tankCapacity multiplier sais how many fuel tanks must be on the rocket for the rocket to pass the Scan. It will be allways approximatly 3.5 tank/engine, but it is 2 engines for mul 1 and 13 engines for mul 0.3.
- tankCapacity does not influence capacity of one tank.
- tank Capacity does not influence the consumption of one engine.

**Comment by gdarai** [comment]
E = Engine, C= guidance PC, S=Seat, B = SateliteBay, T=Fuel Tank
Ok, let's describe some experiments: What is clear for liftoff on default overworld, multipliers = 1
(A) 1E 1C 8T
(B) 2E 1C 5T - isn't this strange? Shouldn't more engines require more fuel?
(C) 3E 1C 6T - the same
**ALSO!!** (D) 1E 1C 1B 7T works, this is wrong, right? And if... YES (E) 1E 1C 1B 1S and only 6T also works

**Summary:** Even though all designs above shows 'ready for liftoff', designs A D and E where the liftoff capacity is filled has acceleration 0 and actually does not get off the ground.
**Suggestion:** Make some minimal liftoff > 0 for the rocket to be valid.

**Comment by gdarai** [comment]
Now, let's try some more:
(A)2E 1C 1S 6T and (B) 2E 1C 1S 1B 6T both works.

Now I have GravityAffectsFuel ON... so let's try the same on MOON:
No, no effect. Still first working is 2E 1C 1S 6T ..... sooo

Summary: We have first warking rockets, **2E1C1S6T is smallest rocket**. Is gravityEffect working at all? This suggests that **Rocket Performance is not influenced by gravity.**

**Comment by gdarai** [comment]
Let's try to change the per-engine thrust to 0.5
OK...
for multiplier 1 it was simple 10*n [N],
for multiplier 0.5 it is [2, 5, 7, 10, 12, 15, 17, 20, 22] so it is roughly 22/10 *n [N] still seems linear.

Hypothesis: If multiplier is [m] and number of engines is [n] the formula is c*m^m1*n where c and m1 are constants calculatable from the known cases.  This gives C=10 and M1=2.32

Ok... in this moment I wanted to make a verification but I found a strange behaviour:
With thrustMultiplier 0.5 and gravity influence on.
When I have rocket (A) 9E 1C 1S it has thrust 22N, but when I add tanks: (B) 9E 1C 1S 2T the thrust jumps up to 45N... this is also quite strange.

**Comment by gdarai** [comment]
Rocket under thrustMul 0.5
(A) E3 1C 1S T6 works. Only Acceleration is 1 instead of expected 3 (3 engines)
**Hypothesis** no matter the multiplier the tanks/engines ratio to make the rocket work will be he same.
Working rocket has still the same ammount of tanks. (B) E4 1C 1S T7 also works. (C) E4 1C 1S T6 shows thrust only 7N ... but I wasn't able to replicate this behaviour once I added T7.
**Summary:** Yes, the thrust is buggy when there is not enough fuel. When there is little fuel, but almost enough the game decreaces the acceleration first. Number of tanks is not that much influenced by the thrustMultiplicator.

**Comment by gdarai** [comment]
Lets try thrustMul 0.25:
First working rocket has (A) E8 1C 1S T8

**Comment by gdarai** [comment]
thrustMul 0.5, tankMul 0.3
First rocket which passed the check was E13 1C1S T48

**Observation:** Tank mul can sure be < 1 and non-integer.
**Observation2:** The fuel tanks are required because they (theoretically) holds less fuel. BUT when I am fueling the ship, their caacity is still the same. Also the rocket has still the same consumption like if I would have only 4 engines, so when I get to the Moon with this minimal rocket, I still have 5/6 fuel-tank full.

**Summary**: tankMul influences how many tanks are required when the rocket is constructed. It does not influence how much fuel they hold, or how much fuel the engine actually consumes.

**Comment by gdarai** [comment]
**Final Recomendations:**
Aside of fixing bugs, i suggest following improvements:
make tankMultiplier to change the consumption rate of engines so the minimal rocket with whatever setting will almost always consume most of it's fuel. But keep that it does not influence the tankCapacity so if somebody will set it to low number it will indeed require a lot more fuel to get into space.

**Offer:**
I don't know which ath you are actually using, but if you will paste it somewhere, people here (me included) would be happy to give you some suggestions for improvements - more realism - or better configurabiity. If you want. It would take some of the weight from your backs and make the mod even more fun.

**Comment by voidsong-dragonfly** [comment]
Fixed in 2.0.0
