### ISSUE TITLE
[Suggestion] Advanced effects for not wearing space suit

### ISSUE THREAD

**Issue by DarkGuardsman** [Advanced-Rocketry/AdvancedRocketry#93]
https://www.youtube.com/watch?v=RjkrqMm52JI

Idea from the video is to add some hardcore negitive effects when explosed to vacume of space. This way exposer is not as simple as losing HP. For example swelling effect can be applied that reduces max HP and movement speed. A chance(.01%) to have the player's heart stop could also be added.

**Comment by TheAmazingSpy** [comment]
How about, a novelty feature is that you are frozen on one side and melting on the other. That would be cool. (remember, it's the side that's facing the sun that melts, and the side facing space freezes)

**Comment by DarkGuardsman** [comment]
As cool as that idea is due to thermaldynamics the other side would still heat up. Nice idea however for bigger objects like space stations or ships.

**Comment by Tronzoid** [comment]
In real life, if you go out into space without a spacesuit, you won't exactly swell up, but you would look more muscular, you would be able to stay conscious for 15 seconds, I think one side of your body gets hot while the other would be freezing cold.

**Comment by DarkGuardsman** [comment]
Might be useful https://www.youtube.com/watch?v=kUfF2MTnqAw
