### ISSUE TITLE
Alternative Sources of Resources

### ISSUE THREAD

**Issue by CTH999** [Advanced-Rocketry/AdvancedRocketry#945]
So, the rocket fuel you use is H2O2, but you just combine 2H,and1O to make it, due to the extra hydrogen created. But, here's an idea. Make more uses for hydrogen, new fuel, AND, add in a gas "Vent", that either voids gases, or behaves like an O2 Vent, meaning use in space, or slowly make atmosphere     un-breathable due to extra hydrogen, or use 02 in it.  Then, you can destroy extra gases, or store it, and rocket fuel is now able to be H2O2, and you can void/store the extra H1, just an idea for realism though.
This would encourage people to use other fuels, unless they need a lot of hydrogen, once you implement other fuels that is. Just an idea though.

Thanks

**Comment by CTH999** [comment]
So, I just though of something. Some moons in our solar system, in real life, might have gases and liquids, such as liquid methane on one of Jupiter's moons, (Forgot which one), which could be used as fuel. That means that if someone where to get to this moon, they can use this fuel, which they can produce artificially. This moon could exist in the default planets, and mod pack authors could make more moons/ planets with this or other fuels on them, and disable this one if needed. And, like wormzjil said in [[Suggestion] adding tier thrusters and ect.](https://github.com/zmaster587/AdvancedRocketry/issues/234)

**Comment by CTH999** [comment]
Also, Non-standard Atmospheres could include acidic ones, requiring an upgraded version of the Space Suit, and if it's very high pressure, it could require a Pressure Protection Module. The Upgraded version could include more tanks for O2, but less for Hydrogen, that way you have more air, and don't breath in acids. But, if there's uses for acids, you can collect the acids, and use them, instead of creating them. Just another atmospheric Idea.

**Comment by CTH999** [comment]
There's two issues that I know of that use exotic matter, and one idea is to have it on planets. But, also, another way to make exotic matter is via a particle accelerator. So, add that in, and you have another source of exotic matter for [adding tier thrusters and ect.](https://github.com/zmaster587/AdvancedRocketry/issues/234) and [Warp Coils](https://github.com/zmaster587/AdvancedRocketry/issues/935)

And, maybe more energy generation options, (Fission, Fusion, Anti-Matter)

P.S. None of these need to be ASAP, I'm just putting them out here for you, on one issue so it isn't 500+

**Comment by CTH999** [comment]
Thanks!

**Comment by voidsong-dragonfly** [comment]
We are not looking to add alternative sources of energy to AR. We are not a standalone mod, and those are best suited to mods that concentrate in that area. Same as generators that run on liquid methane.
