### ISSUE TITLE
Custom WorldTypes for planets

### ISSUE THREAD

**Issue by Thutmose** [Advanced-Rocketry/AdvancedRocketry#980]
Is there currently any way to assign custom worldtypes to planets?  If not, Can it be added as follows:

An extra tag can be added to the planetDefs.xml, which takes the following:
A string name of the WorldType to use.
A string of the generator options for the WorldType.

You can then use WorldType.parseWorldType before registering and generating the dimension.

This would allow for generating worlds from various other mods as planets, or even the vanilla ones like custom flat worlds, etc

**Comment by Thutmose** [comment]
I am adding something very similar to this feature into Pokecube for hopefully later adding in fancy dimensions for legendaries, etc, once I have it functional, I can link the src for that here, and it might help with getting it working for planets

**Comment by Thutmose** [comment]
Seems forge remembers that dimensions were loaded, but not any custom options for them, so that will need to be saved/loaded manually.

Here is what I ended up doing for mine, it could possibly be tweaked/optimized more, but this currently seems to work for using a few strings to generate custom worlds:

Here is a modified version of the WorldServerMulti to allow custom world info:
https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/custom/WorldServerMulti.java

Here are two helper methods for making and loading the actual world:
https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/custom/CustomDimensionManager.java

https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/custom/CustomDimensionManager.java#L61 is just a modifed version of DimensionManager.initDimension to generate the custom WorldServerMulti instead.

https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/custom/CustomDimensionManager.java#L24 generates the worldInfo from strings, then makes the world, then sets it active, it has to replace the existing worlds in this case, as forge seems to replace any "overworld" worldtypes with the same thing used for the main overworld, this can probably be avoided using a custom worldtype (like your planet type) instead here https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/custom/CustomDimensionManager.java#L29 but I have not tested that.
The method then calls the thing I already had for syncing dimids to clients, tbh, not sure how nessisary that actually is, but I was already doing it elsewhere, so I stuck it there.

I then save/load the stuff here: https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/PokecubeDimensionManager.java#L238-L372 I assume this can be done instead wherever you are saving/loading the planet info.

**Comment by Thutmose** [comment]
Confirmed that the method works for generating custom worlds, I tested by editing the planetdefs.xml to set a couple of the worlds as not managed by AR, and then had Pokecube provide some dimensions for them, I then had said dimensions actually generated by dorfgen's world generator, each one using different map and settings :D 

So if you do get time to get around to implementing this, it should work fine

**Comment by voidsong-dragonfly** [comment]
At this point I believe this to be done better through Vanilla dimension datapacks and dimmapping - they can provide generator options we, requisitely, could not, such as (I believe) Terraforged generation options.
